src/main/resources/public/scss/components/_rp-page-members.scss
make assign button to align properly
=> EPMRPP-21097

src/main/resources/public/js/src/project/project.js
…on bts settings page if user has "CUSTOMER" or "MEMBER" project role.
=> Prevented request for getting fields for post bug form

src/main/resources/public/config-server.js, src/main/resources/public/js/src/adminUsers/UsersItemView.js, src/main/resources/public/js/src/components/twitterNewsComponent/TwitterNewsComponent.js, src/main/resources/public/js/src/components/twitterNewsComponent/TwitterNewsItemView.js, src/main/resources/public/js/src/login/loginView.js, src/main/resources/public/scss/admin/all-users.scss, src/main/resources/public/scss/component/twitterNewsComponent/_main.scss, src/main/resources/public/scss/component/twitterNewsComponent/twitter-news-component.scss, src/main/resources/public/scss/component/twitterNewsComponent/twitter-news-item.scss, src/main/resources/public/scss/loginPage/login.scss, src/main/resources/public/templates/components/twitterNewsComponent/tpl-twitter-news-component.html, src/main/resources/public/templates/components/twitterNewsComponent/tpl-twitter-news-item.html, src/main/resources/public/templates/login/tpl-new-login.html
=> Twitter component

src/main/resources/public/js/src/launches/LaunchHeaderView.js, src/main/resources/public/js/src/launches/LaunchPage.js
=> Unsaved filters now will be discarded after leaving launches page.

src/main/resources/public/index.html, src/main/resources/public/scss/components/_rp-common-styles.scss, src/main/resources/public/scss/sections/sidebar.scss, src/main/resources/public/templates/admin/tpl-admin-side-bar.html, src/main/resources/public/templates/index.html, src/main/resources/public/templates/sections/tpl-sidebar.html
=> Back to top btn fix. Sidebar refactoring. Min app height = 415px

src/main/resources/public/js/src/localizations/default.js, src/main/resources/public/js/src/modals/addWidget/FilterSearchView.js, src/main/resources/public/templates/newModals/addWidget/tpl-modal-add-widget-filter-search.html
Change message in case there is no any filter on a project ( when added new widget)
=> Change message no filter

src/main/resources/public/.eslintrc, src/main/resources/public/js/src/core/StickyHeader.js, src/main/resources/public/js/src/launches/LaunchMultipleSelect.js
=> Fix sticky header

src/main/resources/public/js/src/modals/addWidget/FilterSearchView.js
Current filter is not shown as selected in case it has more than 50 filters before
=>  EPMRPP-25283: filter is not shown

src/main/resources/public/js/src/newWidgets/_ChartistWidgetView.js, src/main/resources/public/js/src/newWidgets/widgets/PassingRatePerLaunchChartView.js, src/main/resources/public/js/src/newWidgets/widgets/PassingRateSummaryChartView.js
…for truncating labels in some cases.
=> EPMRPP-26575. Passing rate widgets data calculation refactoring. Fix for truncating labels.

src/main/resources/public/js/src/projectEvents/projectEventsItemView.js, src/main/resources/public/scss/projectEvents/projectEventsView.scss
=> EPMRPP-29480. Old&New Vals for post&attach events on event monitoring page now represents as links

src/main/resources/public/js/src/modals/modalPostBug.js
changes defect type of test-item.
=> EPMRPP-31238.Now post bug backlink stays actual even in case when user changes defect type of test-item.

src/main/resources/public/js/src/newWidgets/_BaseWidgetView.js
=> EPMRPP-31341. Added INTERRUPTED items into redirect for failed items on widgets.

src/main/resources/public/js/src/newWidgets/widgets/launchStatisticsChart/LaunchStatisticsChartAreaView.js, src/main/resources/public/js/src/newWidgets/widgets/launchStatisticsChart/LaunchStatisticsChartBarView.js, src/main/resources/public/js/src/newWidgets/widgets/launchesComparison/LaunchesComparisonView.js, src/main/resources/public/scss/widgets/launch-statistics-chart.scss
Fixed JS error on launches comparison widget(modal).
=> EPMRPP-31357. Added OY Axis for LS widget in fullscreen or print modes.

src/main/resources/public/js/src/updateBackbone.js
=> EPMRPP-31493. Fixed browser history navigation, after close modals with "back" browser button.

app/src/components/inputs/inputCheckbox/inputCheckbox.scss, app/src/components/main/grid/gridBody/gridRow/checkboxCell/checkboxCell.scss, app/src/components/main/paginationToolbar/pageButtons/pageButtons.scss, app/src/components/main/paginationToolbar/pageSizeControl/pageSizeControl.jsx, app/src/components/main/paginationToolbar/paginationToolbar.jsx, app/src/controllers/pagination/withPagination.jsx, app/src/pages/inside/filtersPage/filtersPage.jsx
EPMRPP-33156: Fix pagination size input values.
EPMRPP-34112: Add default sorting to the filters page.
Hide grid checkbox cell on mobile screen.
Fix pagination buttons on mobile screen.
Reset active page on changing page size.
=> Pagination and filters page fixes

app/Readme.md, app/package-lock.json, app/package.json, app/src/index.jsx
Added why-did-you-update tool in dev mode for tracking probable performance issues.
=> added why-did-you-update tool

app/src/controllers/appInfo/reducer.test.js, app/src/controllers/auth/constants.js, app/src/controllers/auth/reducer.js, app/src/controllers/auth/reducer.test.js, app/src/controllers/dashboard/reducer.test.js, app/src/controllers/lang/constants.js, app/src/controllers/lang/reducer.js, app/src/controllers/lang/reducer.test.js, app/src/controllers/modal/actionCreators.js, app/src/controllers/modal/constants.js, app/src/controllers/modal/reducer.js, app/src/controllers/modal/reducer.test.js, app/src/controllers/project/constants.js, app/src/controllers/project/reducer.js, app/src/controllers/project/reducer.test.js, app/src/controllers/user/constants.js, app/src/controllers/user/reducer.js, app/src/controllers/user/reducer.test.js
Other reducers will be refactored and will be covered with tests afterwards.
=> Add reducer tests

app/src/layouts/pageLayout/index.js, app/src/layouts/pageLayout/pageBreadcrumbs/index.js, app/src/layouts/pageLayout/pageBreadcrumbs/pageBreadcrumbs.jsx, app/src/layouts/pageLayout/pageBreadcrumbs/pageBreadcrumbs.scss, app/src/layouts/pageLayout/pageLayout.jsx, app/src/layouts/pageLayout/pageLayout.scss, app/src/pages/inside/dashboardItemPage/dashboardItemPage.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx, app/src/pages/inside/dashboardPage/dashboardPage.jsx, app/src/pages/inside/filtersPage/filtersPage.jsx, app/src/pages/inside/launchesPage/launchesPage.jsx, app/src/pages/inside/membersPage/membersPage.jsx, app/src/pages/inside/stepPage/stepPage.jsx, app/src/pages/inside/suitesPage/suitesPage.jsx, app/src/pages/inside/testsPage/testsPage.jsx, app/src/routes/routesMap.js
=> EPMRPP-35139. Add breadcrumbs to pages

app/src/pages/inside/logsPage/logItemInfo/logItemDetails/index.js, app/src/pages/inside/logsPage/logItemInfo/logItemDetails/logItemDetails.jsx, app/src/pages/inside/logsPage/logItemInfo/logItemDetails/logItemDetails.scss, app/src/pages/inside/logsPage/logItemInfo/logItemInfo.jsx, app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/logItemInfoTabs.jsx
LogItemDetails tab implementation.
=> EPMRPP-35545 React. LogItemDetails tab

app/src/pages/inside/common/itemInfo/durationBlock/durationBlock.scss, app/src/pages/inside/common/itemInfo/itemInfo.jsx, app/src/pages/inside/common/itemInfo/itemInfo.scss, app/src/pages/inside/logsPage/logItemInfo/logItemDetails/logItemDetails.jsx, app/src/pages/inside/logsPage/logItemInfo/logItemDetails/logItemDetails.scss
Please never use `margin` on common components.
=> EPMRPP-36487 LogItemDetails. Fix growth duration showing

app/src/pages/inside/filtersPage/filterGrid/filterName/filterName.scss
=> EPMRPP-35242 fixed hover edit icon

app/src/controllers/testItem/selectors.js
https://jiraeu.epam.com/browse/EPMRPP-35502
=> EPMRPP-35502 No number of run of the launch is in breadcrumbs fix

app/src/controllers/testItem/sagas.js
Signed-off-by: Yana_Zaitsava <Zaitsava_Yana@epam.com>
=> EPMRPP-36663 Change test item request parameters

app/src/common/utils/fetch.test.js
Attempt to fix CI error related to the timeout.
=> Fix occasionally failing fetch tests

app/src/components/widgets/charts/common/tooltip/tooltipWrapper/tooltipWrapper.scss, app/src/components/widgets/charts/failedCasesTrendChart/failedCasesTrendChart.scss, app/src/components/widgets/charts/launchesDurationChart/launchDurationTooltip/index.js, app/src/components/widgets/charts/launchesDurationChart/launchDurationTooltip/launchDurationTooltip.jsx, app/src/components/widgets/charts/launchesDurationChart/launchDurationTooltip/launchDurationTooltip.scss, app/src/components/widgets/charts/launchesDurationChart/launchesDurationChart.jsx, app/src/components/widgets/charts/launchesDurationChart/launchesDurationChart.scss, app/src/components/widgets/charts/launchesDurationChart/tooltip.jsx, app/src/components/widgets/charts/nonPassedTestCasesTrendChart/nonPassedTestCasesTrendChart.scss
use common styles as default tooltipWrapper theme
=> EPMRPP-33456 fix styles for tooltips

app/src/controllers/filter/actionCreators.js, app/src/controllers/filter/constants.js, app/src/controllers/filter/index.js, app/src/controllers/filter/reducer.js, app/src/controllers/filter/reducer.test.js, app/src/controllers/launch/sagas.js, app/src/pages/inside/common/launchFiltersContainer/launchFiltersContainer.jsx, app/src/pages/inside/filtersPage/filterGrid/filterGrid.jsx, app/src/pages/inside/filtersPage/filtersPage.jsx, app/src/pages/inside/launchesPage/launchesPage.jsx
rename Filter field: entities -> conditions
=> EPMRPP-37076 REACT. 404 error occurs after adding a filter and refresh

src/main/resources/public/js/src/launches/logLevel/LogHistoryLine.js, src/main/resources/public/templates/launch/tpl-launch-step-item.html, src/main/resources/public/templates/launchLog/tpl-launch-log-history-line-item.html
EPMRPP-37329 Show growth duration and duration fluctuation on Log view
=> EPMRPP-37329 [THOMPSON REUTERS] Show growth duration and duration fluctuation on Log view

app/src/components/filterEntities/entityItemStartTime.jsx
=> EPMRPP-36884  REACT. Step view. Start time filter options have incorrect names

app/localization/translated/be.json, app/localization/translated/ru.json, app/src/components/fields/dynamicFieldsSection/constants.js, app/src/components/fields/dynamicFieldsSection/dynamicFieldsSection.jsx, app/src/controllers/project/constants.js, app/src/controllers/project/index.js, app/src/controllers/project/selectors.js, app/src/pages/inside/settingsPage/settingsTabs/generalTab/generalTab.jsx, app/src/pages/inside/settingsPage/settingsTabs/generalTab/generalTab.scss, app/src/pages/inside/settingsPage/settingsTabs/generalTab/generalTabsMessages.js
https://jiraeu.epam.com/browse/EPMRPP-37348
https://jiraeu.epam.com/browse/EPMRPP-37346
=> EPMRPP-37348/EPMRPP-37346 React. Adjust general settings with last changes on WS

app/src/pages/inside/dashboardItemPage/widgetWizardModal/widgetWizardContent/wizardInfoSection/wizardInfoSection.jsx
=> EPMRPP-37382 Description of Unique bugs table template is not as expected

app/src/pages/inside/dashboardItemPage/widgetWizardModal/widgetControls/launchStatisticsControls.jsx, app/src/pages/inside/dashboardItemPage/widgetWizardModal/widgetControls/widgetControls.scss, app/src/pages/inside/dashboardItemPage/widgetWizardModal/widgetWizardModal.scss
Added missing beta badge above the Zoom label of the Launch statistics chart
=> EPMRPP-37383: added missing beta badge

app/src/components/main/markdown/markdownViewer/markdownViewer.scss
Issue was already fixed for Chrome. Now it's fixed for Firefox too.
=> EPMRPP-34261-fixed-grid-on-FF

app/src/pages/inside/common/selectedItems/selectedItem/selectedItem.scss, app/src/pages/inside/common/selectedItems/selectedItems.scss
=> EPMRPP-34391: tag shows long launch name now

app/src/pages/admin/serverSettingsPage/common/formController/formController.jsx, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/forms/activeDirectoryAuthForm/activeDirectoryAuthFormFields/activeDirectoryAuthFormFields.jsx, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/forms/ldapAuthForm/ldapAuthForm.jsx, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/forms/ldapAuthForm/ldapAuthFormFields/ldapAuthFormFields.jsx
https://jiraeu.epam.com/browse/EPMRPP-37911
=> EPMRPP-37911 Issues with authorization configuration

app/src/components/inputs/inputTagsSearch/inputTagsSearch.scss, app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/attachments/attachments.stories.jsx
=> EPMRPP-37945: Fix long attributes in firefox and edge

app/src/pages/inside/common/launchFiltersToolbar/launchFiltersToolbar.jsx
EPMRPP-37402
React: Filtering block from Launches level should not be present on test item levels
=> EPMRPP-37402_Filtering_block_from_launces_level_should_not_be_present

app/src/components/fields/fieldErrorHint/fieldErrorHint.scss
fixed the bug where the tooltip message overshadows the input field
=> EPMRPP-37980 moved tooltip message above the input field

app/src/pages/inside/profilePage/configExamplesBlock/configExamplesBlock.jsx, app/src/pages/inside/profilePage/configExamplesBlock/tabsConfig.jsx
Task - https://jiraeu.epam.com/browse/EPMRPP-38201
=> bugfix/EPMRPP-38201 Profile page. Rp properties fix

app/src/components/widgets/charts/common/c3chart/c3chart.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetInfoBlock/widgetInfoBlock.jsx
Task - https://jiraeu.epam.com/browse/EPMRPP-38118
=> bugfix/EPMRPP-38118 Widget preview fix

app/src/components/widgets/charts/launchStatisticsChart/launchStatisticsChart.jsx, app/src/components/widgets/charts/launchStatisticsChart/launchStatisticsChart.scss, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.scss, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widgetHeader/widgetHeader.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.scss
Task - https://jiraeu.epam.com/browse/EPMRPP-38147
=> bugfix/EPMRPP-38147 Launch statistics chart

app/src/common/constants/screenSizeVariables.js, app/src/components/main/paginationToolbar/pageButtons/pageNumberButtons.jsx, app/src/controllers/log/sagas.js, app/src/controllers/log/selectors.js, app/src/controllers/log/utils.js, app/src/controllers/testItem/actionValidators.js, app/src/controllers/testItem/selectors.js, app/src/pages/inside/logsPage/logItemInfo/infoTabs/infoTabs.jsx, app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/attachments/attachments.jsx, app/src/pages/inside/testItemPage/testItemPage.jsx
Task - https://jiraeu.epam.com/browse/EPMRPP-38173
=> EPMRPP-38173 Incorrect request on moving by arrows

app/src/components/widgets/charts/launchExecutionAndIssueStatistics/issueStatisticsChart.jsx, app/src/components/widgets/charts/launchExecutionAndIssueStatistics/launchExecutionChart.jsx
Added click event to chart arches that redirect to STEP view page with the respective filtering
=> EPMRPP-38104: Implement redirect with filters

app/src/pages/admin/allUsersPage/allUsersGrid/allUsersGrid.jsx, app/src/pages/admin/allUsersPage/usersToolbar/actionPanel/actionPanel.jsx
Tasks links:
https://jiraeu.epam.com/browse/EPMRPP-38248
https://jiraeu.epam.com/browse/EPMRPP-38247
=> bugfixes/EPMRPP-38248, EPMRPP-38247

app/src/common/urls.js, app/src/pages/admin/projectsPage/projects/projects.jsx
=> EPMRPP-37180. Perform export all projects.

app/src/controllers/auth/sagas.js, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/statisticsTab/statisticsTab.jsx
Also fix info request not sent after login.
=> EPMRPP-38333: Fix statistics update request.

app/src/components/main/grid/gridBody/gridRow/gridCell/gridCell.scss, app/src/components/main/markdown/markdownViewer/markdownViewer.scss
Also fix word wrapping in markdown viewer
=> EPMRPP-38389: Wrap long columns in grid

app/src/components/inputs/inputFilter/inputFilter.scss
Fix of issue in [first comment](https://jiraeu.epam.com/browse/EPMRPP-38306?focusedCommentId=3897198&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3897198)
=> EPMRPP-38306: Remove native cross icon in filter input in Edge

app/src/pages/inside/common/launchSuiteGrid/defectStatistics/donutChart/donutChart.scss
Fix for [comment](https://jiraeu.epam.com/browse/EPMRPP-38025?focusedCommentId=3904489&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3904489)
=> EPMRPP-38025: Fix defect type counter shift in launches grid

app/src/controllers/fetch/sagas.js, app/src/pages/inside/common/launchFiltersContainer/launchFiltersContainer.jsx, app/src/pages/inside/launchesPage/launchesPage.jsx
Sorting will be implementet in #1237
=> EPMRPP-38393: Reset page number on changing launch filter

app/src/controllers/appInfo/index.js, app/src/controllers/appInfo/selectors.js, app/src/pages/common/settingsPage/autoAnalysisTab/indexActionsBlock/indexActionsBlock.jsx
Task - https://jiraeu.epam.com/browse/EPMRPP-38502
=> EPMRPP-38502 Analyzer settings fix

app/localization/translated/be.json, app/localization/translated/ru.json, app/package-lock.json, app/package.json, app/src/components/main/colorPicker/README.md, app/src/components/main/colorPicker/colorPicker.jsx, app/src/components/main/colorPicker/colorPicker.scss, app/src/components/main/colorPicker/colorPicker.stories.jsx, app/src/components/main/colorPicker/colorPickerSettings.js, app/src/components/main/colorPicker/index.js, app/src/pages/common/settingsPage/defectTypesTab/defectSubType.jsx, app/src/pages/common/settingsPage/defectTypesTab/defectTypesGroup.jsx, app/src/pages/common/settingsPage/defectTypesTab/defectTypesTab.jsx, app/src/pages/common/settingsPage/defectTypesTab/defectTypesTab.scss
Still need to implement:
1. Close color picker when click outside
2. Position input fields according to the design
3. Show locator tooltip on defects name
=> EPMRPP-38511: part of EPMRPP-33317. Edit subtype form + color picker

app/src/pages/inside/dashboardItemPage/modals/common/utils.js, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/constants.js, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/filtersControl/filtersControl.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/cumulativeTrendControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/differentLaunchesComparisonControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/failedCasesTrendControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/flakyTestCasesTableControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/investigatedPercentageOfLaunchesControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/launchDurationControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/launchExecutionAndIssueStatisticsControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/launchStatisticsControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/launchesTableControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/mostFailedTestCasesTableControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/mostTimeConsumingTestCasesControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/notPassedTestCasesTrendControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/overallStatisticsControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/passingRatePerLaunchControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/passingRateSummaryControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/productStatusControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/projectActivityControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/testCasesGrowthTrendControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/uniqueBugsTableControls.jsx, app/src/pages/inside/dashboardItemPage/modals/editWidgetModal/editWidgetControlsSectionForm/editWidgetControlsSectionForm.jsx, app/src/pages/inside/dashboardItemPage/modals/editWidgetModal/editWidgetModal.jsx, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/widgetWizardContent.jsx, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/wizardControlsSection/wizardSecondStepForm/wizardSecondStepForm.jsx, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/wizardControlsSection/wizardThirdStepForm/wizardThirdStepForm.jsx
Task - https://jiraeu.epam.com/browse/EPMRPP-38441
=> EPMRPP-38441 Widget name auto generation fixes

app/src/pages/admin/allUsersPage/usersToolbar/usersEntities.jsx
Search by filters 'Type' and 'Role' should contain 'All' option and looks like 'Criteria for widget' list in widget modal.
=> EPMRPP-38409. Admin. All users. All option in Role and Type filter.

app/src/pages/common/settingsPage/defectTypesTab/defectSubTypeForm.jsx, app/src/pages/common/settingsPage/defectTypesTab/defectTypesTab.jsx, app/src/pages/common/settingsPage/defectTypesTab/defectTypesTab.scss
=> EPMRPP-38512: part of EPMRPP-33317. Add mobile layout, fix cells alignment

app/src/components/inputs/inputFilter/inputFilter.jsx, app/src/components/inputs/inputFilter/inputFilterContainer.jsx
EPMRPP-38561. Contains EPMRPP-38563. Please check and merge this RP after https://github.com/reportportal/service-ui/pull/1348 !
Description: Click on the cross in filter field should set to default all filter values.
=> Epmrpp 38561

app/src/common/urls.js, app/src/controllers/administrate/allUsers/index.js, app/src/pages/admin/allUsersPage/usersToolbar/actionPanel/actionPanel.jsx
EPMRPP-38622. Admin. All users. Exported users fit to displayed users on page now.
=> EPMRPP-38622. Admin.All users. Applying filter conditions to export.

app/src/components/main/breadcrumbs/breadcrumb/breadcrumb.scss, app/src/components/main/breadcrumbs/breadcrumbs.scss
**Before:**
**Afrer:**
**Before:**
**Afrer:**
=> EPMRPP-38460. Launches page. Fix breadcrumbs overflow

app/src/components/main/tooltips/hoverableTooltip/README.md, app/src/components/main/tooltips/hoverableTooltip/hoverableTooltip.scss, app/src/components/main/tooltips/hoverableTooltip/hoverableTooltip.stories.jsx, app/src/components/main/tooltips/hoverableTooltip/withHoverableTooltip.jsx, app/src/pages/common/settingsPage/defectTypesTab/defectSubType.jsx, app/src/pages/inside/common/infoLine/defectTypeBlock/defectTypeBlock.jsx, app/src/pages/inside/common/launchSuiteGrid/defectStatistics/donutChart/donutChart.jsx, app/src/pages/inside/launchesPage/modals/launchImportModal/launchIcon/iconStateIndicators/invalidIcon.jsx
=> EPMRPP-38613: part of EPMRPP-33317, add defect type's tooltip with locator. Refactor withHoverable tooltip to use react-popper

app/src/controllers/testItem/utils.js
Case link: http://localhost:3000/#internal/launches/all/60/10968/10969?item1Params=page.page%3D1%26page.size%3D1&item2Params=page.page%3D1%26page.size%3D1
=> Fix level calculation in case of 1 step item in the list

app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/logItemActivity/logItemActivity.jsx
`activityItem.details` is undefined.
=> EPMRPP-38689. Log view. History of actions exception

app/src/common/utils/routingUtils.js, app/src/components/widgets/charts/launchExecutionAndIssueStatistics/issueStatisticsChart.jsx, app/src/components/widgets/charts/launchExecutionAndIssueStatistics/launchExecutionChart.jsx, app/src/components/widgets/charts/launchStatisticsChart/launchStatisticsChart.jsx, app/src/components/widgets/charts/launchesComparisonChart/launchesComparisonChart.jsx, app/src/components/widgets/charts/launchesDurationChart/launchesDurationChart.jsx, app/src/components/widgets/charts/testCasesGrowthTrendChart/testCasesGrowthTrendChart.jsx, app/src/controllers/administrate/projects/actionCreators.js, app/src/controllers/administrate/projects/constants.js, app/src/controllers/administrate/projects/index.js, app/src/controllers/administrate/projects/sagas.js, app/src/controllers/filter/sagas.js, app/src/controllers/launch/sagas.js, app/src/controllers/pages/actionCreators.js, app/src/controllers/testItem/sagas.js, app/src/pages/admin/projectsPage/projectMenu/projectMenu.jsx, app/src/pages/admin/projectsPage/projectName/projectName.jsx, app/src/pages/admin/projectsPage/projectsPage.jsx, app/src/pages/admin/projectsPage/projectsPanelView/projectPanel/projectPanel.scss, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/serverSettingsTabs.jsx, app/src/pages/common/settingsPage/settingsPage.jsx, app/src/pages/inside/common/suiteTestToolbar/actionPanel/actionPanel.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx, app/src/pages/inside/logsPage/logToolbar/logToolbar.jsx
Exclude `redirect` function in ordinal page navigation, saving history of page visits.
=> EPMRPP-37759, EPMRPP-38541. Redirect. Saving browser history on redirect

app/src/components/inputs/inputTagsSearch/inputTagsSearch.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/tagsControl.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/flakyTestCasesTableControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/mostFailedTestCasesTableControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/mostTimeConsumingTestCasesControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/passingRatePerLaunchControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/productStatusControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/projectActivityControls.jsx, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/wizardControlsSection/wizardFirstStepForm/widgetTypeSelector/widgetTypeItem/widgetTypeItem.jsx, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/wizardControlsSection/wizardFirstStepForm/widgetTypeSelector/widgetTypeItem/widgetTypeItem.scss
Highlight selected type of widget with bold.
Fix inputTagsSearch api.
Fix parseLaunchNames parser.
=> EPMRPP-37853. Add new widget. Widget wizard improvements

app/src/pages/admin/allUsersPage/allUsersGrid/projectsAndRolesColumn/rolesRow/rolesRow.jsx
Project name in projct list component should work like a link to project in projects page.
=> EPMRPP-38665. Admin. All users. Clickable project name in project list component.

app/src/pages/inside/common/launchFiltersToolbar/filterList/filterList.scss, app/src/pages/inside/common/launchFiltersToolbar/launchFiltersToolbar.jsx, app/src/pages/inside/common/launchFiltersToolbar/launchFiltersToolbar.scss
=> EPMRPP-36975. LaunchFiltersToolbar. Fix filters overlapping

app/localization/translated/be.json, app/localization/translated/ru.json, app/src/common/urls.js, app/src/pages/inside/dashboardPage/dashboardPage.jsx
300 items by default and Not found message.
=> EPMRPP-37146. Search on dashboards page

app/localization/translated/be.json, app/localization/translated/ru.json, app/src/pages/inside/filtersPage/filterDeleteModal/filterDeleteModal.jsx, app/src/pages/inside/filtersPage/filtersPage.jsx
=> EPMRPP-35241. FiltersPage. Show warning when we delete foreign filter

app/src/pages/outside/registrationPage/registrationPageContainer.jsx
=> EPMRPP-34139: show error message from response

app/src/pages/common/settingsPage/notificationsTab/constants.js, app/src/pages/common/settingsPage/notificationsTab/notificationCaseList/caseListItem/caseListItem.jsx
Task - https://jiraeu.epam.com/browse/EPMRPP-38714
=> EPMRPP-38714 Settings. Notifications. Empty attribute key fix

app/src/common/utils/fetch.js, app/src/store/configureStore.js
=> EPMRPP-38308: add axios interceptor to log out the user when it's unauthorize response status

app/src/pages/admin/allUsersPage/modals/addUserModal/addUserModal.jsx
Fixed restrictions and validation for Full Name and Default Project fields in Add User Modal.
=> EPMRPP-38686, EPMRPP-38684. Fixed restrictions and validation in Add User Modal.

app/src/controllers/testItem/index.js, app/src/controllers/testItem/selectors.js, app/src/pages/inside/common/defectLink/defectLink.jsx
=> EPMRPP-36930: Fix filter change on navigation by statistics.

app/src/components/widgets/charts/launchExecutionAndIssueStatistics/issueStatisticsChart.jsx, app/src/components/widgets/charts/launchExecutionAndIssueStatistics/launchExecutionAndIssueStatistics.scss, app/src/components/widgets/charts/launchExecutionAndIssueStatistics/launchExecutionChart.jsx
For adjust, charts in a container just need to call `chat.resize` method in `onIssuesChartCreated`.
For change the font size of title inside of pie chart I used css-class `small-view`.
Before:
Afrer:
=> EPMRPP-38526. Dashboard. LaunchExecutionAndIssueStatistics.

app/src/pages/inside/dashboardPage/modals/addEditModal/addEditModal.jsx
1. Go to RP -> Dashboard tab
2. Click 'Add new dashboard' button
3. Enter more than 128 symbols in the field 'Name'
**Actual result:**
It is possible to continue entering symbols in the field
=> EPMRPP-37108 - REACT. Possible to continue entering symbols into 'Name' field in 'Add new dashboard' modal in the amount of more than 128

app/src/pages/inside/launchesPage/modals/launchMergeModal/launchMergeModal.jsx
=> EPMRPP-38830: merge launches attributes properly

app/src/pages/inside/common/launchSuiteGrid/launchSuiteGrid.scss
=> EPMRPP-35503: remove redundant padding

app/src/pages/inside/common/defectTypeSelector/defectTypeSelector.scss
=> EPMRPP-38740: show defect types in one column on mobile

app/src/controllers/testItem/sagas.js, app/src/controllers/testItem/utils.js
Set level to Suite when current level is "" to display Suites toolbar
=> EPMRPP-38319: set default level to Suite Level

app/src/pages/common/settingsPage/defectTypesTab/defectTypesTab.jsx
The order of the defect types should be as in version 4:
Product bug
Automation Bug
System Issue
No Defect
To Investigate
=> EPMRPP-38916 - REACT. Incorrect order of the defect types

app/src/controllers/auth/sagas.js
Confirmation messages on login and log out of RP in the status bar are missed
=> EPMRPP-38835 - React: Confirmation messages on login and log out of RP in status bar are missed

app/src/routes/routesMap.js
=> EPMRPP-39000: GET with invalid params

app/src/components/widgets/charts/passingRatePerLaunch/passingRatePerLaunch.jsx
Need to call resizeHelper on each rerender.
=> EPMRPP-37982. PassingRatePerLaunch widget. Fix bar chart labels

app/package-lock.json, app/package.json, app/src/components/inputs/regExEditor/README.md, app/src/components/inputs/regExEditor/codemirror-regex-mode.js, app/src/components/inputs/regExEditor/index.js, app/src/components/inputs/regExEditor/regExEditor.jsx, app/src/components/inputs/regExEditor/regExEditor.scss, app/src/components/inputs/regExEditor/regExEditor.stories.jsx
=> EPMRPP-38847. Regex editor with syntax highlighting.

app/src/pages/inside/profilePage/configExamplesBlock/tabsConfig.jsx
Expected:
'Tags' should be replaced with 'attributes'
=> EPMRPP-39092 - React: Update 'Configuration examples' with parameter 'attribute' on Profile page

app/localization/translated/be.json, app/localization/translated/ru.json, app/src/pages/inside/logsPage/logItemInfo/logItemInfo.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.scss, app/src/pages/inside/stepPage/stepGrid/defectType/patternAnalyzedLabel/index.js, app/src/pages/inside/stepPage/stepGrid/defectType/patternAnalyzedLabel/patternAnalyzedLabel.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/patternAnalyzedLabel/patternAnalyzedLabel.scss, app/src/pages/inside/stepPage/stepGrid/defectType/patternAnalyzedLabel/patternAnalyzedTooltip/index.js, app/src/pages/inside/stepPage/stepGrid/defectType/patternAnalyzedLabel/patternAnalyzedTooltip/patternAnalyzedTooltip.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/patternAnalyzedLabel/patternAnalyzedTooltip/patternAnalyzedTooltip.scss, app/src/pages/inside/stepPage/stepGrid/stepGrid.jsx
Added PA label (works as designed).
AA label doesn't consist corresponding icon because I didn't get it in time. So I'll create extra PR for adding icon later.
=> EPMRPP-38848. PA label on step and log view.

app/src/pages/common/settingsPage/defectTypesTab/defectSubType.jsx, app/src/pages/common/settingsPage/defectTypesTab/defectTypesGroup.jsx
Steps:
Login RP as user with role less than PM (e.g., MEMBER) on the project
Go to the project>Settings>Defect types
Verify view
Expected:
The page is disabled to be modified
Actual:
The page has enabled view on UI
=> EPMRPP-39103 - React: User with role with less than PROJECT_MANAGER should not modify defect types

app/src/controllers/filter/sagas.js
request in case at least one option is filled in correctly
=> EPMRPP-38772: filter - at least one option is filled in correctly

app/src/components/widgets/charts/launchExecutionAndIssueStatistics/launchExecutionAndIssueStatistics.jsx, app/src/components/widgets/charts/overallStatisticsChart/overallStatisticsChart.jsx
=> Launch execution and issue statistics widget remove unnecessary decorator

app/src/common/urls.js, app/src/pages/inside/launchesPage/launchesPage.jsx
In case at least one launch is in progress status, the request on
GET http://host:port/api/v1/
{project_name}
/launch/status?ids=<launchId>
should be send every 5 seconds.
=> EPMRPP-38244 - React: Send request on GET status of launches are in progress every 5 seconds

app/src/components/main/modal/modalLayout/modalLayout.jsx
=> EPMRPP-39007: ie11 - modal is positioned wrong

app/src/components/widgets/charts/overallStatisticsChart/overallStatisticsPanel.jsx, app/src/components/widgets/charts/overallStatisticsChart/progressBar.scss, app/src/components/widgets/charts/overallStatisticsChart/totalStatistics.jsx
The issue refer 'Overall statistics' widget
Please show '0' statistics for requested field in case it is not returned from back end in response
=> EPMRPP-38910 - React: In case the requested content field is not returned in response, show '0' statistics for this field

app/src/components/fields/fieldErrorHint/fieldErrorHint.jsx
=> EPMRPP-39247 - React: On the login field, UI shows 128 symbols, on the element (F12), it shows 256

app/src/common/constants/defectTypes.js, app/src/components/widgets/charts/launchExecutionAndIssueStatistics/issueStatisticsChart.jsx, app/src/components/widgets/charts/launchStatisticsChart/launchStatisticsChart.jsx, app/src/components/widgets/charts/overallStatisticsChart/overallStatisticsPanel.jsx, app/src/controllers/project/index.js, app/src/controllers/project/selectors.js
=> EPMRPP-39049: reopened legend defects order

app/src/components/main/grid/data.js, app/src/components/main/grid/grid.jsx, app/src/components/main/grid/grid.stories.jsx, app/src/components/main/grid/gridBody/gridBody.jsx, app/src/components/main/grid/gridBody/gridRow/gridRow.jsx, app/src/components/main/grid/gridBody/gridRow/gridRow.scss, app/src/components/main/grid/gridBody/nestedGridBody.jsx, app/src/components/main/grid/gridBody/nestedGridBody.scss, app/src/pages/inside/common/durationBlock/durationBlock.scss, app/src/pages/inside/logsPage/logsGrid/logsGrid.jsx, app/src/pages/inside/logsPage/logsGrid/logsGrid.scss, app/src/pages/inside/logsPage/logsGrid/nestedStepHeader/index.js, app/src/pages/inside/logsPage/logsGrid/nestedStepHeader/nestedStepHeader.jsx, app/src/pages/inside/logsPage/logsGrid/nestedStepHeader/nestedStepHeader.scss
=> EPMRPP-38666. Nested steps grid.

app/src/pages/admin/projectsPage/projectsPage.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgets.jsx
These features need to be hidden only for the beta version (**v5** branch).
=> EPMRPP-39318: Show hidden features for release version

app/src/components/inputs/inputDropdownSorting/inputDropdownSorting.scss, app/src/pages/inside/common/filtersSorting/filtersSorting.scss
@Andrew-Omelchenko I don't understand why you introduced z-index in `.launches-sort` in 
`filtersSorting.scss` at #1648 . So, please, review, will it work properly now.
=> EPMRPP-39414. Launches. Fix Sort by overlay in filter.

app/package-lock.json, app/package.json
https://github.com/axios/axios/issues/1098
=> Update axios to fix security issue (CVE-2019-10742)

app/src/layouts/pageLayout/pageBreadcrumbs/pageBreadcrumbs.jsx, app/src/layouts/pageLayout/pageBreadcrumbs/pageBreadcrumbs.scss, app/src/pages/inside/common/dashboardPageHeader/addDashboardButton/addDashboardButton.scss
=> EPMRPP-38868. Fix breadcrumbs overflow.

app/src/components/widgets/charts/overallStatisticsChart/overallStatisticsPanel.jsx, app/src/components/widgets/charts/overallStatisticsChart/totalStatistics.jsx
relevant fields with zero values should be displayed
=> EPMRPP-38910: only relevant fields with zero values

app/src/pages/inside/common/modals/editItemsModal/editItemsModal.jsx
=> EPMRPP-39501. Bulk edit launches and items. Fix submit with empty description

app/src/common/urls.js, app/src/components/main/grid/gridBody/gridRow/gridRow.jsx, app/src/components/widgets/index.js, app/src/components/widgets/tables/index.js, app/src/components/widgets/tables/mostPopularPatterns/README.md, app/src/components/widgets/tables/mostPopularPatterns/data.js, app/src/components/widgets/tables/mostPopularPatterns/index.js, app/src/components/widgets/tables/mostPopularPatterns/mostPopularPatterns.jsx, app/src/components/widgets/tables/mostPopularPatterns/mostPopularPatterns.scss, app/src/components/widgets/tables/mostPopularPatterns/mostPopularPatterns.stories.jsx, app/src/components/widgets/tables/mostPopularPatterns/patternGrid/index.js, app/src/components/widgets/tables/mostPopularPatterns/patternGrid/patternGrid.jsx, app/src/components/widgets/tables/mostPopularPatterns/patternGrid/patternGrid.scss, app/src/components/widgets/tables/mostPopularPatterns/patternGrid/patternGridColumns.jsx, app/src/components/widgets/tables/mostPopularPatterns/secondLevelPanel.jsx, app/src/components/widgets/utils.js, app/src/controllers/testItem/index.js, app/src/pages/inside/dashboardItemPage/modals/common/img/wdgt-most-popular-patterns-inline.svg, app/src/pages/inside/dashboardItemPage/modals/common/widgets.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
=> EPMRPP-39614. Widget Most popular patterns.

app/src/components/widgets/tables/mostPopularPatterns/mostPopularPatterns.jsx, app/src/components/widgets/tables/mostPopularPatterns/mostPopularPatterns.scss, app/src/components/widgets/tables/mostPopularPatterns/patternGrid/patternGrid.jsx, app/src/components/widgets/tables/mostPopularPatterns/patternGrid/patternGrid.scss, app/src/components/widgets/tables/mostPopularPatterns/patternGrid/patternGridColumns.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
Fixed resetting attribute on change level. Fixed scroll overflow on second level. Changed link to launch: on launch name click instead of test items counts.
=> EPMRPP-38298. PA widget. Bug fixes.

app/src/components/inputs/inputSwitcher/inputSwitcher.jsx, app/src/components/inputs/inputSwitcher/inputSwitcher.scss, app/src/components/inputs/inputSwitcher/inputSwitcher.stories.jsx
According to design "on" and "off" state in disabled mode have the same gray color. It will be improved later.
=> EPMRPP-39567. Fix readonly state for small switcher.

app/localization/translated/be.json, app/localization/translated/ru.json, app/src/components/fields/fieldErrorHint/fieldErrorHint.jsx, app/src/components/fields/fieldProvider.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/customColumnsControl/customColumnItem/customColumnItem.scss, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/customColumnsControl/customColumnsControl.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/customColumnsControl/customColumnsControl.scss, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/productStatusControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgets.jsx, app/src/pages/inside/dashboardItemPage/modals/editWidgetModal/editWidgetModal.jsx, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/widgetWizardContent.jsx
Also fixes EPMRPP-37384 issue, and is part of EPMRPP-33466 user story.
=> EPMRPP-38826: product status js error in wizard

app/src/components/fields/dynamicFieldsSection/constants.js, app/src/components/fields/dynamicFieldsSection/dynamicFieldShape.js, app/src/components/fields/dynamicFieldsSection/dynamicFieldsSection.jsx, app/src/components/fields/dynamicFieldsSection/fields/arrayField/arrayField.jsx, app/src/components/fields/dynamicFieldsSection/fields/dateField/dateField.jsx, app/src/components/fields/dynamicFieldsSection/fields/dropdownField/dropdownField.jsx, app/src/components/fields/dynamicFieldsSection/utils.js, app/src/components/fields/fieldErrorHint/fieldErrorHint.jsx, app/src/components/integrations/elements/bts/btsPropertiesForIssueForm/btsPropertiesForIssueForm.jsx, app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.scss, app/src/components/integrations/elements/integrationSettings/integrationForm/integrationForm.jsx, app/src/components/integrations/elements/integrationSettings/integrationSettings.jsx, app/src/pages/inside/stepPage/modals/postIssueModal/constants.js, app/src/pages/inside/stepPage/modals/postIssueModal/postIssueModal.jsx, app/src/pages/inside/stepPage/modals/postIssueModal/utils.js
**Also in this PR:**
Default property for value in the `btsFormFields` supports different properties for different BTS.
Post issue modal default credentials [fix](https://jiraeu.epam.com/browse/EPMRPP-39612).
=> EPMRPP-39672 Post issue fields validation / EPMRPP-39612

app/localization/translated/be.json, app/localization/translated/ru.json, app/src/common/img/cancel-inline.svg, app/src/components/containers/fullscreen/fullscreen.jsx, app/src/components/containers/fullscreen/fullscreen.scss, app/src/components/containers/fullscreen/index.js, app/src/pages/inside/dashboardItemPage/dashboardItemPage.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx
=> EPMRPP-37271. Full screen mode only according to the internal size of the tab.

app/src/pages/common/membersPage/membersGrid/personalInfo/personalInfo.jsx, app/src/pages/common/membersPage/membersGrid/personalInfo/personalInfo.scss
Also, I added a title for name and login.
=> EPMRPP-38620: React. Project members. Wrong representation of long user names

app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/logItemActivity/historyItem/historyItem.jsx
=> EPMRPP-40136. To show the matched pattern name on the History of Actions.

app/src/components/main/grid/gridBody/gridRow/gridRow.scss, app/src/controllers/log/index.js, app/src/pages/inside/common/stackTrace/stackTrace.jsx, app/src/pages/inside/common/stackTrace/stackTrace.scss, app/src/pages/inside/common/stackTraceMessageBlock/index.js, app/src/pages/inside/common/stackTraceMessageBlock/stackTraceMessageBlock.jsx, app/src/pages/inside/common/stackTraceMessageBlock/stackTraceMessageBlock.scss, app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/editToInvestigateDefectModal.jsx, app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/itemsList/itemsListRow/itemsListRow.jsx, app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/itemsList/itemsListRow/itemsListRow.scss, app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/itemsList/itemsListRow/messageBlock/index.js, app/src/pages/inside/stepPage/modals/testItemDetailsModal/testItemDetailsModal.jsx, app/src/pages/inside/stepPage/modals/testItemDetailsModal/testItemDetailsModal.scss
=> EPMRPP-40105. Collapsable stack trace messages.

app/src/pages/inside/common/itemInfo/attributesBlock/attributesBlock.scss
=> EPMRPP-38525. Add extra space between attributes.

app/src/pages/inside/stepPage/stepGrid/defectType/issueList/issue/issue.scss
=> EPMRPP-40088. Fix display of linked ticket with long ID

app/src/pages/inside/common/stackTraceMessageBlock/stackTraceMessageBlock.jsx, app/src/pages/inside/common/stackTraceMessageBlock/stackTraceMessageBlock.scss, app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/editToInvestigateDefectModal.scss, app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/itemsList/itemsList.jsx, app/src/pages/inside/stepPage/modals/editDefectModals/editToInvestigateDefectModal/itemsList/itemsListRow/itemsListRow.jsx
=> EPMRPP-41422/41388. Add level of log on 'Edit defect type' modal

app/src/common/utils/routingUtils.js, app/src/common/utils/validation.js, app/src/controllers/filter/withFilter.jsx, app/src/pages/inside/dashboardPage/dashboardPage.jsx, app/src/pages/inside/dashboardPage/dashboardPageToolbar/dashboardPageToolbar.jsx, app/src/pages/inside/filtersPage/filterPageToolbar/filterPageToolbar.jsx
The problem was related to the operation of comparing query parameters in the `updatePageProperties` action handler (`controllers/pages/sagas.js`).
Fixed in [`app/src/common/utils/routingUtils.js`](https://github.com/reportportal/service-ui/pull/1987/files#diff-35d5c90d658372e08bd85ffdec92a0e6R31).
=> EPMRPP-41427 Multiple requests after page refresh with search string

app/src/components/main/attributeList/editableAttribute/attributeEditor/attributeEditor.jsx, app/src/components/main/attributeList/editableAttribute/attributeEditor/attributeInput/attributeInput.jsx, app/src/components/main/attributeList/editableAttribute/editableAttribute.jsx
Also remove redux-form from attribute editor.
=> EPMRPP-41169: Disable attribute submit in case of duplicate.

app/package-lock.json, app/package.json
Issue was fixed in the [0.7.8 c3 chart library release](https://github.com/c3js/c3/releases/tag/v0.7.8)
=> EPMRPP-41112 Update c3 chart library to fix error in FF

app/src/components/integrations/containers/integrationSettingsContainer/integrationSettingsContainer.jsx
Don't send the name of the integration if it isn't updated.
=> EPMRPP-41163 Default integration name

app/src/controllers/project/constants.js
Update on ui side project attribute from 'pattern.analysis.enabled' to 'analyzer.isAutoPatternAnalyzerEnabled'
=> EPMRPP-42450: Error on start pattern analysis manually in case the automatic analysis is set to OFF

app/src/pages/inside/launchesPage/modals/launchMergeModal/launchMergeModal.jsx
Addition line between descriptions for markdown
=> EPMRPP-33861 merge launches wrong description

app/src/pages/inside/stepPage/retries/retries.jsx, app/src/pages/inside/stepPage/retries/retries.scss, app/src/pages/inside/stepPage/retries/retriesContainer.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.jsx, app/src/pages/inside/stepPage/stepGrid/itemInfoWithRetries/retriesBlock/retriesBlock.jsx
As part of this defect, the following problem https://github.com/reportportal/reportportal/issues/743 was fixed by adding a scroll
=> EPMRPP-42448: REACT.Launches. Incorrect illustration of the retries ' Stack trace' on the Step View

app/src/controllers/itemsHistory/sagas.js, app/src/pages/inside/common/suiteTestToolbar/actionPanel/actionPanel.jsx, app/src/pages/inside/historyPage/historyPage.jsx, app/src/pages/inside/historyPage/historyToolbar/historyToolbar.jsx, app/src/pages/inside/historyPage/historyView/historyControls/historyControls.scss
Waiting for https://github.com/reportportal/service-ui/pull/2207
=> EPMRPP-43963 History page. Provide access from list view & filter list view

app/localization/translated/be.json, app/localization/translated/ru.json, app/src/common/urls.js, app/src/controllers/log/reducer.js, app/src/controllers/log/sagas.js, app/src/controllers/log/selectors.js, app/src/controllers/log/utils.js, app/src/pages/inside/logsPage/historyLine/historyLine.jsx, app/src/pages/inside/logsPage/historyLine/historyLineItem/historyLineItem.jsx, app/src/pages/inside/logsPage/historyLine/historyLineItem/historyLineItemContent/historyLineItemBadges/historyLineItemBadges.jsx, app/src/pages/inside/logsPage/historyLine/historyLineItem/historyLineItemContent/historyLineItemContent.jsx, app/src/pages/inside/logsPage/historyLine/historyLineItem/historyLineItemContent/historyLineItemContent.scss
Waiting for https://github.com/reportportal/service-ui/pull/2210
=> EPMRPP-44711 History. Change history items mapping logic on logs page

Dockerfile-full, Makefile, src/main/resources/public/scss/loginPage/login.scss
=> EPMRPP-39299 Fix login page elements everflow

app/src/components/inputs/inputDropdown/inputDropdown.jsx, app/src/components/inputs/inputDropdown/inputDropdown.scss, app/src/components/main/markdown/markdownEditor/markdownEditor.scss, app/src/pages/inside/stepPage/modals/testItemDetailsModal/testItemDetailsModal.jsx, app/src/pages/inside/stepPage/modals/testItemDetailsModal/testItemDetailsModal.scss
I reduced description editor height and add popper to the dropdown for avoiding extra scroll while it's opened in the edge of screen.
=> EPMRPP-44968. Design fixes for edit to investigate defect modal.

app/src/controllers/log/attachments/sagas.js, app/src/controllers/log/attachments/utils.js
=> Fix formatting for attachments with "text/json" type

app/src/pages/outside/loginPage/pageBlocks/serviceVersionsBlock/serviceVersionsBlockWithData.jsx
=> Fix error when receiving non-semver service versions on login screen.

app/package-lock.json, app/package.json, app/src/components/main/markdown/markdownViewer/markdownViewer.jsx
Closes reportportal/reportportal#768
=> EPMRPP-45044: Add support for HTML in markdown

app/src/common/constants/screenSizeVariables.js, app/src/components/main/paginationToolbar/pageButtons/pageNumberButtons.jsx, app/src/components/widgets/common/chartjs/chartjs.jsx, app/src/components/widgets/index.js, app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/chartjsConfig.js, app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/cumulativeTrendChart.jsx, app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/legend/cumulativeChartLegend.jsx, app/src/pages/admin/allUsersPage/allUsersGrid/projectsAndRolesColumn/projectsAndRolesColumn.jsx, app/src/pages/admin/projectsPage/projectName/projectName.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx, app/src/pages/inside/logsPage/logItemInfo/infoTabs/infoTabs.jsx, app/src/pages/inside/testItemLogsToolbar/testItemLogsToolbar.jsx
The controls panel won't be shown if the width of the widget less then 767px (it's our value for XS screen size)
=> EPMRPP-45113: Dasboard and widget. Cumulative trend chart. Add a possibility to resize a widget.

app/src/controllers/plugins/index.js, app/src/controllers/plugins/sagas.js, app/src/controllers/plugins/utils.js
- as part of this defect, I just replaced one URL with the other on addIntegration 
- the other steps will be changed as part of this defect https://jiraeu.epam.com/browse/EPMRPP-46995
=> EPMRPP-46748: UI: URL to setup integration with LDAP is incorrect

app/src/components/main/navigationTabs/navigationTabs.jsx, app/src/controllers/plugins/index.js, app/src/controllers/plugins/uiExtensions/index.js, app/src/controllers/plugins/uiExtensions/registerPlugin.jsx, app/src/controllers/plugins/uiExtensions/selectors.js, app/src/pages/common/settingsPage/settingsPage.jsx, app/src/routes/routesMap.js
=> EPMRPP-47707: Allow plugins to add own tabs to project settings

app/src/components/main/modal/modalLayout/modalField/modalField.jsx, app/src/components/main/modal/modalLayout/modalFooter/modalFooter.jsx, app/src/components/main/modal/modalLayout/modalLayout.jsx
Add noMinHeight prop to ModalField.
=> EPMRPP-49369: Add submit confirmation to ModalLayout

app/src/components/main/markdown/markdownViewer/markdownViewer.jsx, app/src/components/main/markdown/markdownViewer/markdownViewer.scss, app/src/components/main/markdown/markdownViewer/markdownViewer.test.jsx, app/src/pages/inside/logsPage/logsGrid/logsGrid.jsx, app/src/pages/inside/logsPage/logsGrid/nestedStepHeader/nestedStepHeader.jsx, app/src/pages/inside/logsPage/logsGrid/nestedStepHeader/nestedStepHeader.scss
Fix code blocks rendered as HTML.
=> EPMRPP-50917: Add markdown support to nested step header

.golangci.yml, .travis.yml
Fixes issues with golang linter on Travis CI
=> travis issue fix

app/src/components/integrations/containers/integrationInfoContainer/infoSection/infoSection.jsx, app/src/components/integrations/containers/integrationInfoContainer/integrationInfoContainer.jsx
These changes need to display the plugin's description
=> EPMRPP-57227: Plugin structure. Upload plugin/ add a new tab to Setting page. Implement a basic plugin structure

app/src/components/inputs/inputDropdown/inputDropdown.jsx, app/src/components/inputs/inputDropdown/inputDropdown.stories.jsx, app/src/components/main/dependentFieldsControl/dependentFieldsControl.jsx, app/src/components/main/dependentFieldsControl/dependentFieldsControl.scss, app/src/components/main/dependentFieldsControl/index.js, app/src/pages/inside/filtersPage/filtersPage.jsx, app/src/pages/inside/logsPage/attachmentActions/actionsItem/actionsItem.jsx, app/src/pages/inside/logsPage/attachmentActions/actionsItem/actionsItem.scss, app/src/pages/inside/logsPage/attachmentActions/actionsItem/index.js, app/src/pages/inside/logsPage/attachmentActions/attachmentActions.jsx, app/src/pages/inside/logsPage/attachmentActions/attachmentActions.scss
Component sample to test the behavior:
```
import { useState } from 'react';
import { InputDropdown } from 'components/inputs/inputDropdown';
import { DependentFieldsControl } from 'components/main/dependentFieldsControl';
const options = [
{
value: 'V1',
label: 'Value 1',
disabled: false,
},
{
value: 'V2',
label: 'Value 2',
disabled: false,
},
];
export const TestComponent = () => {
const [value, setValue] = useState('');
function handleChange(newValue) {
setValue(newValue);
}
const mainControl = {
component: <InputDropdown value={value} onChange={handleChange} options={options} />,
postfix: 'Of',
};
const dependentFields = [
{
value: 'V1',
fields: [
{ postfix: 'For', component: mainControl.component, id: 'attr' },
{ postfix: '%', component: mainControl.component, id: 'dt' },
],
},
{ …
```
=> EPMRPP-57596 Add dependent fields control

app/src/components/widgets/multiLevelWidgets/cumulativeTrendChart/legend/cumulativeChartLegend.scss
Reverts reportportal/service-ui#2511
=> Revert "EPMRPP-57663: Cumulative trend chart. Re-write with new logic. Change widget view - remove the tumbler"

app/src/controllers/testItem/sagas.js
[#1282](https://github.com/reportportal/reportportal/issues/1282)
=> EPMRPP-59007 - Create filter on launches page without saving and open launch in new tabs leads to infinite loading

app/src/components/integrations/containers/integrationInfoContainer/infoSection/infoSection.jsx
Fix switcher bug on detailed plugin page
=> EPMRPP-57551 Fix switcher bug on detailed plugin page

app/localization/translated/be.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/src/components/main/modal/darkModalLayout/darkModalLayout.jsx, app/src/components/main/modal/darkModalLayout/darkModalLayout.scss, app/src/pages/inside/stepPage/modals/editDefectModals/makeDecisionModal/makeDecisionModal.jsx, app/src/pages/inside/stepPage/modals/editDefectModals/messages.js
PR contain 60878 & 60886 tickets
=> EPMRPP-60878 - move unsaved changes notification to scrollable content remove scroll from defect types list

app/src/pages/inside/logsPage/defectEditor/itemHeader/itemHeader.jsx, app/src/pages/inside/logsPage/defectEditor/itemHeader/itemHeader.scss, app/src/pages/inside/stepPage/stepGrid/defectType/autoAnalyzedLabel/autoAnalyzedLabel.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/autoAnalyzedLabel/autoAnalyzedLabel.scss
update AA label according to last comment in the ticket and revert [ab77057d](https://github.com/reportportal/service-ui/commit/ab77057db0cc22482f2b1f5d689d7b23954a0938)
=> EPMRPP-61339 - fix AA label according to design

app/src/common/utils/validation/asyncValidation.js, app/src/pages/inside/profilePage/modals/forceUpdateModal/forceUpdateModal.jsx
Admin part. Fixed project name validation
=> EPMRPP-53473 Admin part. Fixed project name validation

app/package-lock.json
[62334](https://jiraeu.epam.com/browse/EPMRPP-62334)
[62335](https://jiraeu.epam.com/browse/EPMRPP-62335)
=> EPMRPP-62334 - fix vulnerabilities

app/src/pages/inside/stepPage/modals/makeDecisionModal/makeDecisionModal.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.jsx
typeof issue.comment is 'string'
=> EPMRPP-63017: editing of defect type undefined

app/src/components/containers/initialDataContainer/initialDataContainer.jsx, app/src/components/main/analytics/EmptyAnalyticsWrapper.jsx, app/src/components/main/analytics/index.js, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/widgetWizardContent.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx, app/src/pages/inside/filtersPage/filterGrid/filterOptions/filterOptions.jsx
Can be merged only after testing on dev env.
=> [DNM] EPMRPP-64481 Repair analytics when it turned off

app/src/pages/inside/common/infoPanel/viewTabs/viewTabs.jsx, app/src/pages/inside/logsPage/logItemInfo/logItemInfo.jsx, app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/logItemInfoTabs.jsx, app/src/pages/inside/logsPage/logsPage.jsx
Can be merged after https://github.com/reportportal/service-ui/pull/2791 testing
=> EPMRPP-64570 Fix log view pagination

app/src/components/main/analytics/events/common/testItemPages/actionEventsCreators.js, app/src/components/main/analytics/events/historyPageEvents.js, app/src/components/main/analytics/events/launchesPageEvents.js, app/src/components/main/analytics/events/logPageEvents.js, app/src/components/main/analytics/events/stepPageEvents.js, app/src/components/main/analytics/events/suitesPageEvents.js, app/src/components/main/analytics/events/testsPageEvents.js, app/src/pages/inside/stepPage/stepPage.jsx, app/src/pages/inside/suitesPage/suitesPage.jsx, app/src/pages/inside/testItemPage/testItemPage.jsx, app/src/pages/inside/testsPage/testsPage.jsx
* EPMRPP-68485: GA fix wrong event category in test level
* EPMRPP-68485: fix ga events on tests page / refactoring
* EPMRPP-68485: refactoring ga events
Co-authored-by: Aleksandr Zyabrev <aleksandr_zyabrev@epam.com>
=> EPMRPP-68485: fix ga events on tests page (#2886)

app/src/pages/inside/profilePage/accessTokenBlock/accessTokenBlock.scss
=> EPMRPP-69119 || fix icon position

app/src/components/inputs/input/input.scss, app/src/components/inputs/inputTextArea/inputTextArea.scss, app/src/pages/inside/stepPage/modals/postIssueModal/postIssueModal.jsx
In the scope of this task, I will change the border width for error input according to the new design.
=> EPMRPP-73377 || Wrong color for unchecked checkboxes

app/src/controllers/uniqueErrors/sagas.js, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/uniqueErrorsGrid.jsx
* EPMRPP-74112 || fix wrong result for unique errors filter if all errors are new
* EPMRPP-74112 || code review fixes - 1
=> EPMRPP-74112 || fix wrong result for unique errors filter if all errors are new

app/src/components/extensionLoader/extensionLoader.jsx, app/src/components/extensionLoader/hooks.js, app/src/components/extensionLoader/utils.js, app/src/controllers/plugins/uiExtensions/actions.js, app/src/controllers/plugins/uiExtensions/constants.js, app/src/controllers/plugins/uiExtensions/overrideExtension.js, app/src/controllers/plugins/uiExtensions/reducer.js, app/src/controllers/plugins/uiExtensions/registerPlugin.jsx, app/src/controllers/plugins/uiExtensions/selectors.js
See example plugin [readme](https://github.com/reportportal/plugin-example#ui) how to use.
=> EPMRPP-76395 || Local plugins overriding for dev mode

app/src/componentLibrary/attributeEditor/attributeEditor.jsx, app/src/componentLibrary/autocompletes/common/autocompleteOption/autocompleteOption.scss, app/src/components/containers/attributeListContainer/attributeListContainer.jsx
Was back previous behaviour [comment](https://github.com/reportportal/service-ui/pull/3164#discussion_r914499742)
=> EPMRPP-78285 || fix autocomplete option height

app/src/components/widgets/multiLevelWidgets/componentHealthCheckTable/columns/nameColumn.jsx, app/src/pages/inside/common/modals/editItemModal/editItemModal.jsx, app/src/pages/inside/common/modals/editItemsModal/editItemsModal.jsx, app/src/pages/inside/stepPage/modals/testItemDetailsModal/testItemDetailsModal.jsx
EPMRPP-77946 || Component health check column tooltip, EPMRPP-78035 || Min length for hint fix
=> EPMRPP-77946 || Component health check column tooltip, EPMRPP-78035 | Fix

app/src/componentLibrary/autocompletes/common/autocompleteOption/autocompleteOption.jsx, app/src/componentLibrary/autocompletes/common/autocompleteOption/autocompleteOption.scss, app/src/componentLibrary/autocompletes/singleAutocomplete/singleAutocomplete.jsx
EPMRPP-78114 || Autocomplete active item style fix, added default selected item, ability to click on whole new item line
=> EPMRPP-78114 || Attributes new item upgrade

app/src/components/integrations/integrationProviders/jiraIntegration/jiraConnectionFormFields/jiraConnectionFormFields.jsx, app/src/components/main/notification/notificationList/notificationListItem/notificationItem.jsx, app/src/pages/common/settingsPage/notificationsTab/notificationsTab.jsx, app/src/pages/inside/projectSettingsPageContainer/content/defectTypes/defectTypeRow/defectTypeRow.jsx, app/src/pages/inside/projectSettingsPageContainer/content/defectTypes/defectTypeRow/defectTypeRow.scss
EPMRPP-79144 || Defect Type locator redesign, EPMRPP-79624 || Extra asterisk for Jira Server field, EPMRPP-79629 || Crash fix on Edit Notification tab in admin, EPMRPP-79635 || Defect type text fix for events
=> EPMRPP-79144 || Defect Type locator redesign, small bug fixes

app/src/common/constants/projectRoles.js
Delete CUSTOMER and OPERATOR from roles.
=> EPMRPP-77769 || Refactoring roles

app/src/controllers/plugins/uiExtensions/createImportProps.js
Add dottedPreloader to plugin.
=> EPMRPP-78594 || Update plugin status on launch view

app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/recipientsContainer/recipientsContainer.jsx
Now autocomplete starting from 1 symbol.
=> EPMRPP-79329 || Update autocomplete in Notification

app/src/controllers/administrate/projects/sagas.js
Request body must contains ID instead of KEY.
=> EPMRPP-79759 || Error when delete project bug fix routing

app/src/controllers/administrate/projects/sagas.js
Now when user add project. In response body we have projectKey for this project.
=> EPMRPP-79759 || Get projectKey on addProject

app/src/layouts/appLayout/appHeader/appHeader.jsx, app/src/layouts/appLayout/appSidebar/appSidebar.jsx, app/src/layouts/common/projectSelector/projectSelector.jsx
Fix issue when ProjectSelector displays projectKeY instead of projectName.
=> EPMRPP-79759 || ProjectSelector displays projectKey instead of name

app/src/controllers/administrate/projects/actionCreators.js, app/src/controllers/administrate/projects/sagas.js, app/src/controllers/user/reducer.js, app/src/controllers/user/reducer.test.js, app/src/controllers/user/sagas.js, app/src/layouts/common/projectSelector/projectSelector.jsx, app/src/pages/admin/projectsPage/projectsPage.jsx, app/src/routes/routesMap.js
On add project we need to pass organizationId and projectKey. AssignedProjects now contains organizationSlug field.
=> EPMRPP-79768 || Update creating project

app/src/pages/outside/loginPage/pageBlocks/loginBlock/loginForm/loginForm.jsx
Replace Russian "С" with English "C".
=> Fix autoComplete=off for login page

app/src/common/urls.js, app/src/controllers/log/attachments/sagas.test.js, app/src/controllers/log/attachments/selectors.test.js, app/src/controllers/plugins/uiExtensions/sagas.test.js
A fix to allow install RP to path: https://github.com/reportportal/kubernetes/issues/116
=> Ingress to path

app/src/components/main/analytics/events/ga4Events/dashbordsPageEvents.js, app/src/pages/inside/dashboardItemPage/dashboardItemPage.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/radioGroupControl.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/passingRatePerLaunchControls.jsx, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/passingRateSummaryControls.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
This events are send when user change ratio based option in PRperLaunch and PRSummary widgets.
=> EPMRPP-80554 || Add event to PRperLaunch and PRSummary

app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationHeader/integrationHeader.jsx, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationInfo.jsx
[EPMRPP-79185](https://jiraeu.epam.com/browse/EPMRPP-79185) 
Don't show extra button in header if haven't integrations
---
Before: 
---
After: 
---
=> EPMRPP-79185 || remove extra button if haven't integrations

app/src/common/urls.js, app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleAutocomplete.jsx, app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleDownshift.jsx, app/src/controllers/project/actionCreators.js, app/src/controllers/project/constants.js, app/src/controllers/project/reducer.js, app/src/controllers/project/sagas.js, app/src/controllers/project/selectors.js, app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/launchNamesContainer/launchNamesContainer.jsx
Implement warning message and highlighting inexistent launch names in edit and duplicate modals. Add endpoint which returns all existing launch names.
=> EPMRPP-78657 || Notification of an inexistent launch

app/localization/translated/be.json, app/localization/translated/ru.json, app/localization/translated/uk.json
[EPMRPP-79975](https://jiraeu.epam.com/browse/EPMRPP-79975)
remove translate for true/false
=> EPMRPP-79975 || remove translate for true/false

app/localization/translated/be.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/mostPopularPatternsControls.jsx
[EPMRPP-81231](https://jiraeu.epam.com/browse/EPMRPP-81231)
add validation message attribute key in top20 widget
Before: 
[video](https://jiraeu.epam.com/secure/attachment/2132592/81231.mp4)
---
After: 
https://user-images.githubusercontent.com/70880574/213494059-09ddaee0-b5cf-4425-8b28-f4fd24553a3a.mp4
---
=> EPMRPP-81231 || add validation message for attribute key in top20 widget

app/src/components/integrations/elements/integrationSettings/integrationSettings.jsx, app/src/components/integrations/integrationProviders/activeDirectoryIntegration/activeDirectorySettings/activeDirectorySettings.jsx, app/src/components/integrations/integrationProviders/emailIntegration/emailSettings/emailSettings.jsx, app/src/components/integrations/integrationProviders/jiraIntegration/jiraSettings/jiraSettings.jsx, app/src/components/integrations/integrationProviders/ldapIntegration/ldapSettings/ldapSettings.jsx, app/src/components/integrations/integrationProviders/rallyIntegration/rallySettings/rallySettings.jsx, app/src/components/integrations/integrationProviders/samlIntegration/samlSettings/samlSettings.jsx, app/src/components/integrations/integrationProviders/sauceLabsIntegration/sauceLabsSettings/sauceLabsSettings.jsx, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrations.jsx, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationInfo.jsx
[EPMRPP-81163](https://jiraeu.epam.com/browse/EPMRPP-81163)
Before: 
https://jiraeu.epam.com/secure/attachment/2129811/screencast%202022-12-15%2017-09-10.mp4
---
After: 
https://user-images.githubusercontent.com/70880574/214232563-c0fa79b4-af97-4b87-89bc-9a2bc20dd086.mp4
---
=> EPMRPP-81163 || fix navigation menu not display after removal integration

app/package-lock.json, app/package.json, app/src/components/main/analytics/AnalyticsWrapper.jsx, app/src/components/main/analytics/events/ga4Events/index.js, app/src/components/main/analytics/events/ga4Events/sideBarEvents.js, app/src/components/main/analytics/events/sidebarFooterEvents.js, app/src/controllers/appInfo/selectors.js, app/src/layouts/appLayout/appSidebar/appSidebar.jsx, app/webpack/base.config.js
Also test event for launch icon was added
=> EPMRPP-82062 || Add code GA4

app/src/pages/common/modals/importModal/constants.js, app/src/pages/common/modals/importModal/importFileIcon/iconStateIndicators/defaultIcon.jsx, app/src/pages/common/modals/importModal/importFileIcon/iconStateIndicators/uploadIndicator.jsx, app/src/pages/common/modals/importModal/importFileIcon/importFileIcon.jsx, app/src/pages/common/modals/importModal/importModal.jsx, app/src/pages/inside/launchesPage/launchesPage.jsx
Add the ability to import the .xml file`s extension.
=> EPMRPP-81154 || Launch import improvements

app/localization/translated/be.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/src/components/main/analytics/events/common/testItemPages/actionEventsCreators.js, app/src/components/main/analytics/events/index.js, app/src/components/main/analytics/events/launchesPageEvents.js, app/src/components/main/analytics/events/stepPageEvents.js, app/src/components/main/analytics/events/suitesPageEvents.js, app/src/components/main/analytics/events/testsPageEvents.js, app/src/components/main/analytics/events/uniqueErrorsPageEvents.js, app/src/components/main/analytics/utils.js, app/src/pages/inside/common/defectTypeTooltip/defectTypeTooltip.jsx, app/src/pages/inside/common/infoLine/infoLine.jsx, app/src/pages/inside/common/itemInfo/itemInfo.jsx, app/src/pages/inside/launchesPage/modals/launchAnalysisModal/launchAnalysisModal.jsx, app/src/pages/inside/launchesPage/modals/launchPatternAnalysisModal/launchPatternAnalysisModal.jsx, app/src/pages/inside/stepPage/retries/retries.jsx, app/src/pages/inside/stepPage/retries/retriesContainer.jsx, app/src/pages/inside/stepPage/retries/retriesStackTrace/connectedRetriesStackTrace.jsx, app/src/pages/inside/stepPage/retries/retriesStackTrace/index.js, app/src/pages/inside/stepPage/retries/retriesStackTrace/retriesStackTrace.jsx, app/src/pages/inside/stepPage/retries/retriesStackTrace/retriesStackTrace.scss, app/src/pages/inside/stepPage/stepGrid/itemInfoWithRetries/itemInfoWithRetries.jsx
Also renamed `EDIT_ICON_CLICK` to `CLICK_EDIT_ICON` for consistency.
=> EPMRPP-82632 || GA4. Add events for test item pages

app/src/pages/common/uiExtensionPage/uiExtensionPage.jsx
Fix `Cannot read properties of undefined (reading 'newLayout')`
=> EPMRPP-83304 || Admin ui extension page

app/src/componentLibrary/attributeEditor/attributeEditor.jsx
This PR handles the additional scenario in https://jiraeu.epam.com/browse/EPMRPP-78550
=> EPMRPP-78550 || Handle additional case in attr accessibility

app/src/components/main/grid/gridBody/gridRow/gridRow.scss, app/src/components/main/grid/gridBody/nestedGridRow/nestedGridRow.jsx, app/src/components/main/grid/gridBody/nestedGridRow/nestedGridRow.scss, app/src/pages/inside/logsPage/logsGrid/nestedStepHeader/nestedStepHeader.scss
The hover effect was removed only after discussing it with BA and UI/UX designer.
=> EPMRPP-84530 || Adjust Load current step functionality

app/src/componentLibrary/checkbox/checkbox.scss, app/src/componentLibrary/radioGroup/radioButton/radioButton.scss, app/src/componentLibrary/toggle/toggle.jsx, app/src/componentLibrary/toggle/toggle.scss
Some styles from checkbox, radio button were also changed
=> EPMRPP-845560 || Accessibility.Toggle

app/src/componentLibrary/dropdown/dropdown.scss, app/src/componentLibrary/fieldText/fieldText.scss
=> EPMRPP-81548 || Update components colors and opacity

app/src/components/extensionLoader/hooks.js, app/src/pages/common/uiExtensionPage/uiExtensionPage.jsx
Verified on http://dev.epmrpp.reportportal.io/ui/#administrate/plugin/billing/allProjects
=> EPMRPP-87396 || Error on extension page

app/src/components/integrations/elements/bts/btsPropertiesForIssueForm/btsPropertiesForIssueForm.jsx
Please check the comments from the task.
Should be tested with the latest version of Gitlab plugin.
=> EPMRPP-87564 || Disable issue type field for all BTS plugins

app/src/components/widgets/singleLevelWidgets/charts/investigatedTrendChart/config/timelineConfig.js, app/src/pages/inside/uniqueErrorsPage/messages.js, docs/10-design.md
=> Fixing typo(s)

app/src/layouts/appLayout/projectSidebar/organizationsControl/organizationsPopover/organizationsItem/organizationsItem.jsx, app/src/layouts/appLayout/projectSidebar/organizationsControl/organizationsPopover/organizationsItem/organizationsItem.scss, app/src/layouts/appLayout/projectSidebar/organizationsControl/organizationsPopover/organizationsItem/projectItem/index.js, app/src/layouts/appLayout/projectSidebar/organizationsControl/organizationsPopover/organizationsItem/projectItem/projectItem.jsx, app/src/layouts/appLayout/projectSidebar/organizationsControl/organizationsPopover/organizationsItem/projectItem/projectItem.scss, app/src/layouts/appLayout/projectSidebar/organizationsControl/organizationsPopover/organizationsPopover.jsx
=> EPMRPP-90104 || List of organizations is not scrolled to active project

app/src/layouts/appLayout/demoBanner/demoBanner.jsx
=> EPMRPP-89865 || UI crashes on the demo instance if GitHub authentication has not been set up

app/src/layouts/common/appSidebar/appSidebar.jsx, app/src/layouts/common/appSidebar/appSidebar.scss, app/src/layouts/common/appSidebar/userAvatar/userAvatar.jsx, app/src/layouts/common/appSidebar/userControl/userControl.scss
=> EPMRPP-90109 || Logo and menu item name are not highlighted together

app/.prettierrc, app/src/components/buttons/ghostButton/ghostButton.scss, app/src/pages/inside/logsPage/logItemInfo/defectDetails/defectDetails.jsx
=> EPMRPP 79349 || "Make decision" button has wrong color on Log level

app/src/components/main/modal/modalLayout/modalLayout.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
=> EPMRPP-83058 || The 'Delete widget' modal is not closed when clicking on the 'Delete' button while widget is loading 

app/src/pages/common/membersPage/modals/inviteUserModal/inviteUserModal.jsx
=> EPMRPP-89665 || Assign user modal. Remove prefix for error messages

app/src/controllers/project/sagas.js
=> EPMRPP-90608 ||  'All Notifications' toggle becomes enabled in case creating the first rule

app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.jsx
=> EPMRPP-90897 || Notification rule details validation fix

app/src/pages/inside/projectSettingsPageContainer/content/notifications/ruleGroup/ruleGroup.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/utils.js
=> EPMRPP-90904 || "Email" and "Slack" toggles states is not preserved after reloading the page

app/src/pages/inside/stepPage/modals/linkIssueModal/linkIssueFields/linkIssueFields.jsx, app/src/pages/inside/stepPage/modals/linkIssueModal/linkIssueModal.jsx
=> EPMRPP-90397 || Fix autocomplete for Rally issue ID in linked issues

app/src/pages/inside/launchesPage/modals/importLaunchModal/importLaunchModal.jsx
=> EPMRPP-89999 || Rename plugin params

app/src/pages/inside/common/modals/retentionPolicy/hooks.js
=> EPMRPP-91279 || Launch Attributes are deleted

app/src/components/main/analytics/events/launchesPageEvents.js, app/src/pages/inside/launchesPage/modals/importLaunchModal/importLaunchModal.jsx
=> EPMRPP-90638 || Update import event. Adding type

app/src/components/widgets/singleLevelWidgets/tables/projectActivity/activities/launch.jsx, app/src/components/widgets/singleLevelWidgets/tables/projectActivity/projectActivity.jsx
=> EPMRPP-90462 || change event message and date fix

app/src/components/main/analytics/events/launchesPageEvents.js, app/src/pages/inside/common/launchSuiteGrid/hamburger/hamburger.jsx, app/src/pages/inside/common/modals/retentionPolicy/markAsImportantModal/markAsImportantModal.jsx, app/src/pages/inside/common/modals/retentionPolicy/unmarkAsImportantModal/unmarkAsImportantModal.jsx, app/src/pages/inside/launchesPage/launchesPage.jsx, app/src/pages/inside/launchesPage/modals/deleteLaunchModal/deleteLaunchModal.jsx, app/src/pages/inside/launchesPage/modals/deleteLaunchModal/footer/footer.jsx
=> EPMRPP-90637 || Add events for Launches Retention Policy

app/src/controllers/log/sagas.js
=> EPMRPP-91264 || Extra request for 'locations' is sent in debug mode

app/src/common/utils/referenceDictionary.js
=> EPMRPP-91201 || Update the Documentation link

app/src/componentLibrary/sidebar/sidebar.scss, app/src/layouts/common/appSidebar/userControl/userControl.scss
=> EPMRPP-92351 || Sidebar has extra spacing

app/package-lock.json, app/package.json, app/src/controllers/organizations/organization/selectors.js, app/src/controllers/organizations/projects/selectors.js, app/src/pages/organization/organizationProjectsPage/organizationProjectsPage.jsx, app/src/pages/organization/organizationProjectsPage/projectsListTable/projectsListTable.jsx, app/src/pages/organization/organizationProjectsPage/projectsListTable/projectsListTable.scss, app/src/pages/organization/organizationProjectsPage/projectsPageHeader/projectsPageHeader.jsx, app/src/pages/organization/organizationProjectsPage/projectsPageHeader/projectsPageHeader.scss, app/src/pages/organization/projectTeamPage/projectTeamListTable/projectTeamListTable.jsx
=> EPMRPP-92349 || Several UI bugs related to "Projects" page

app/src/controllers/log/sagas.js
=> EPMRPP-91264 || Extra location request is sent for error log messages

app/src/controllers/log/sagas.js
=> EPMRPP-91264 || Add Condition for Fetching Error Log Location in Detailed Log View Mode

app/src/components/main/analytics/events/ga4Events/projectSettingsPageEvents.js, app/src/pages/inside/projectSettingsPageContainer/content/notifications/LinkComponent/LinkComponent.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/ruleGroup/ruleGroup.jsx
=> EPMRPP-92500 || GA4. Issues with events for Notifications

app/src/components/main/analytics/events/ga4Events/projectSettingsPageEvents.js
=> EPMRPP-92500 || There is no 'condition' configure Integration event

app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx
=> EPMRPP-92623 || Resize widget functionality is broken

app/src/controllers/plugins/uiExtensions/createImportProps.js
=> EPMRPP-89717 || Plugins import props. Fix preloader name for backward compatibility

app/src/components/main/analytics/events/common/widgetPages/utils.js, app/src/components/main/analytics/events/ga4Events/dashboardsPageEvents.js, app/src/pages/inside/dashboardItemPage/dashboardItemPage.jsx, app/src/pages/inside/dashboardItemPage/modals/common/utils.js, app/src/pages/inside/dashboardItemPage/modals/editWidgetModal/editWidgetModal.jsx, app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/widgetWizardContent.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx, app/src/pages/inside/dashboardItemPage/widgetsGrid/widgetsGrid.jsx
=> EPMRPP-92625 & EPMRPP-92629 || Remove extra GA events

app/src/components/main/analytics/events/ga4Events/dashboardsPageEvents.js
=> EPMRPP-92634 || add new widget element name fix

app/src/components/main/analytics/events/ga4Events/dashboardsPageEvents.js, app/src/pages/inside/dashboardItemPage/modals/common/utils.js, app/src/pages/inside/dashboardPage/dashboardList/EmptyDashboards/emptyDashboards.jsx
=> EPMRPP-92634 || "Add New Dashboard" button" event is missing

app/src/common/utils/timeDateUtils.js
=> EPMRPP-91800 || If log doesn't have microseconds in log_time in database, log view crashes with TypeError

app/src/controllers/uniqueErrors/sagas.js, app/src/controllers/uniqueErrors/selectors.js, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/uniqueErrorsGrid.jsx, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsPage.jsx
=> EPMRPP-93055 || EPMRPP-93054 || Bugfixes related to unique errors

app/src/components/main/analytics/AnalyticsWrapper.jsx, app/src/components/main/analytics/events/ga4Events/loginPageEvents.js, app/src/components/main/analytics/events/loginPageEvents.js, app/src/pages/outside/loginPage/loginPage.jsx, app/src/pages/outside/loginPage/socialSection/socialsBlock/socialsBlock.jsx
=> EPMRPP-89423 || Add 2 events for Login page

app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx, app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.scss, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationCollection/integrationCollectionItem/integrationCollectionItem.jsx, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationCollection/integrationCollectionItem/integrationCollectionItem.scss
=> EPMRPP-87094 || Integration connection section layout is broken with long integration name

app/src/components/extensionLoader/extensionTypes.js, app/src/components/extensionLoader/utils.js, app/src/controllers/plugins/uiExtensions/overrideExtension.js
=> Fix local plugins overriding

app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/clusterItemsGridRow/clusterItemsGridRow.jsx, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/clusterItemsGridRow/clusterItemsGridRow.scss, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/uniqueErrorsGrid.jsx, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/uniqueErrorsGrid.scss
=> EPMRPP-93091 || Unique error page is blinking when expanding cluster

app/src/controllers/appInfo/selectors.js
=> EPMRPP-89691 || Update event parameter "pattern_analysis"

app/src/components/widgets/singleLevelWidgets/tables/uniqueBugsTable/uniqueBugsTable.jsx
=> EPMRPP-93183 || "Unique bugs table" widget is broken

app/src/componentLibrary/dropdown/dropdown.jsx, app/src/componentLibrary/dropdown/dropdown.scss, app/src/componentLibrary/dropdown/dropdownOption/dropdownOption.jsx, app/src/componentLibrary/dropdown/dropdownOption/dropdownOption.scss
=> EPMRPP-88471 || Update dropdown options width

app/package-lock.json, app/package.json, app/src/components/integrations/modals/addIntegrationModal/addIntegrationModal.jsx, app/src/components/integrations/modals/deleteIntegrationModal/deleteIntegraionModal.jsx, app/src/components/main/hexColorPicker/hexColorPicker.scss, app/src/pages/inside/projectSettingsPageContainer/content/analyzerContainer/modals/removeIndexModal/removeIndexModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/defectTypes/modals/addEditDefectTypeModal/addEditDefectTypeModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/defectTypes/modals/deleteDefectTypeModal/deleteDefectTypeModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/elements/ruleList/ruleItem/plain/ruleItem.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/deleteNotificationCaseModal/deleteNotificationCaseModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/ruleGroup/ruleGroup.jsx, app/src/pages/inside/projectSettingsPageContainer/content/patternAnalysis/modals/createPatternAnalysisModal/createPatternAnalysisModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/patternAnalysis/modals/deletePatternRuleModal/deletePatternRuleModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/patternAnalysis/modals/editPatternModal/editPatternModal.jsx
EPMRPP-93343 || inconsistencies in modals
=> EPMRPP-93338 || automation attributes and EPMRPP-93343 || inconsistencies in modals

app/src/layouts/organizationsControl/organizationsPopover/organizationsItem/organizationsItemContentHeaderWithTooltip/organizationsItemContentHeaderWithTooltip.jsx
=> EPMRPP-92683 || Fix the position of the tooltip

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/components/fields/dynamicFieldsSection/fields/arrayField.jsx, app/src/components/integrations/integrationProviders/jiraIntegration/messages.js, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationCollection/integrationCollectionItem/integrationCollectionItem.jsx
=> EPMRPP-93122 || "New value" button is displayed & EPMRPP-93089 ||  Rename "BTS password" field 

app/src/pages/admin/pluginsPage/pluginsListItems/pluginsListItems.jsx
=> EPMRPP-93483 || Rename Import Launches tab in Administrate>Plugins page

app/src/controllers/organizations/projects/constants.js
=> EPMRPP-93661 || Error when opening project list via the Open button

app/src/common/constants/pluginsFilter.jsx
=> EPMRPP-93483 || Rename Import Launches in Navigation

app/src/common/constants/pluginsGroupTypes.js, app/src/components/integrations/containers/integrationInfoContainer/instancesSection/instancesSection.jsx, app/src/components/main/analytics/events/logPageEvents.js, app/src/components/main/analytics/events/pluginsPageEvents.js, app/src/components/main/analytics/events/uniqueErrorsPageEvents.js, app/src/pages/admin/pluginsPage/pluginsFilter/pluginsFilter.jsx, app/src/pages/admin/pluginsPage/pluginsTabs/installedTab/installedTab.jsx, app/src/pages/inside/logsPage/logsGrid/flexibleLogTime/flexibleLogTime.jsx, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/uniqueErrorsGrid.jsx
=> EPMRPP-93588 || Add events for category "Plugins", "Unique Errors", "Log"

app/src/componentLibrary/dropdown/dropdown.scss
=> EPMRPP-93474 || Dropdown list doesn't match field width

app/src/pages/inside/stepPage/stepGrid/groupHeader/groupHeader.jsx
=> EPMRPP-88981 || Broken links on filtered Launches page

app/src/common/urls.js
=> EPMRPP-84703 || Autocomplete with spec symbols works incorrect

app/package-lock.json, app/package.json, app/src/pages/inside/stepPage/stepGrid/defectType/issueList/issue/issueWithTooltip.scss
=> EPMRPP-92433 || Icons issues

app/src/layouts/organizationsControl/organizationsPopover/organizationsPopover.jsx, app/src/layouts/organizationsControl/organizationsPopover/organizationsPopover.scss
=> EPMRPP-94185 || Incorrect margins for focus area on the Search field

app/src/components/main/paginationWrapper/paginationWrapper.scss
=> EPMRPP-93770 || There is no border on the top of the pagination area

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationHeader/integrationHeader.jsx, app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/messages.js
=> EPMRPP-89375 || Unnecessary "Add Project Integration" button is displayed after creating Project integration

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleAutocomplete.jsx, app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/recipientsContainer/recipientsContainer.jsx
=> EPMRPP-81969 || Recipients field there is no validation message

app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/recipientsContainer/recipientsContainer.jsx
=> EPMRPP-81969 || new email fix

app/src/controllers/organizations/projects/sagas.js
=> EPMRPP-94810 || Missing updates in the header

app/src/components/fields/dynamicFieldsSection/constants.js, app/src/components/fields/dynamicFieldsSection/dynamicFieldsSection.jsx
=> EPMRPP-94816 || Jira Cloud. Implement functionality to add Assignee

app/src/layouts/organizationsControl/organizationsPopover/organizationsPopover.scss
=> EPMRPP-94586 || Wrong paddings for the search filed in sidebar popover

app/src/components/main/analytics/events/ga4Events/helpAndServiceVersionsEvents.js, app/src/components/main/analytics/events/sidebarFooterEvents.js, app/src/layouts/common/appSidebar/appSidebar.jsx, app/src/layouts/common/appSidebar/helpAndService/FAQcontent/FAQContent.jsx, app/src/layouts/common/appSidebar/helpAndService/modals/requestSupportModal/requestSupportModal.jsx, app/src/layouts/common/appSidebar/helpAndService/modals/versionsOfConnectedServicesModal/serviceVersion/serviceVersion.jsx, app/src/layouts/common/appSidebar/helpAndService/servicesContent/servicesContent.jsx
=> EPMRPP-92505 || GA for Help and Service versions

app/src/components/main/paginationWrapper/paginationWrapper.scss
=> EPMRPP-94764 || The pagination section is not fixed at the bottom

app/src/controllers/uniqueErrors/sagas.js
=> EPMRPP-91716 || Error occurs when running Unique Error analysis

app/src/components/main/analytics/AnalyticsWrapper.jsx, app/src/components/main/analytics/utils.js, app/src/controllers/appInfo/selectors.js
=> EPMRPP-78832 || Add custom parameter organization_id

app/src/pages/organization/organizationProjectsPage/modals/addProjectModal.jsx
=> EPMRPP-94765 || Update the state of action buttons

app/src/pages/organization/organizationProjectsPage/projectsListTable/projectsListTable.jsx, app/src/pages/organization/organizationUsersPage/organizationUsersListTable/organizationUsersListTable.jsx
=> EPMRPP-96296 || Update relationships to stats to align with backend changes

app/src/components/integrations/elements/integrationSettings/integrationForm/integrationForm.jsx, app/src/components/main/analytics/events/common/pluginsPage/actionEventCreators.js, app/src/components/main/analytics/events/pluginsPageEvents.js, app/src/components/main/analytics/events/settingsPageEvents.js
=> EPMRPP-93816 || Add event for plugins configuration view

app/src/components/buttons/ghostButton/ghostButton.scss
=> EPMRPP-95797 || 'Make Decision' button doesn't appear as disabled

app/src/controllers/organization/projects/actionCreators.js, app/src/controllers/organization/projects/constants.js, app/src/controllers/organization/projects/index.js, app/src/controllers/project/sagas.js, app/src/pages/common/index.js, app/src/pages/instance/organizationsPage/organizationsPage.jsx, app/src/pages/organization/organizationProjectsPage/organizationProjectsPage.jsx, app/src/pages/organization/organizationProjectsPage/projectsListTable/projectName/projectName.jsx
=> EPMRPP-96135 || Modal window doesn't open upon clicking

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/components/fields/searchField/searchField.jsx, app/src/controllers/filter/withFilter.jsx, app/src/pages/common/membersPage/modals/inviteUserModal/inviteUserModal.jsx, app/src/pages/instance/organizationsPage/organizationsPageHeader/organizationsPageHeader.jsx, app/src/pages/instance/organizationsPage/organizationsPageHeader/organizationsPageHeader.scss, app/src/pages/organization/organizationProjectsPage/projectsPageHeader/projectsPageHeader.jsx, app/src/pages/organization/projectTeamPage/projectTeamListTable/projectTeamListTable.jsx
=> EPMRPP-96394 || EPMRPP-96117 || EPMRPP-96388 || Search icon has incorrect color

app/src/layouts/organizationLayout/organizationSidebar/organizationSidebar.jsx
=> EPMRPP-96409 || Organization Settings option is visible for Member

app/src/components/main/paginationWrapper/paginationWrapper.jsx, app/src/components/main/paginationWrapper/paginationWrapper.scss, app/src/pages/instance/allUsersPage/allUsersPage.jsx, app/src/pages/instance/organizationsPage/organizationsPage.jsx, app/src/pages/instance/organizationsPage/organizationsPanelView/organizationsPanelView.jsx, app/src/pages/instance/organizationsPage/organizationsPanelView/organizationsPanelView.scss, app/src/pages/organization/common/membersPage/membersListTable/membersListTable.jsx, app/src/pages/organization/common/membersPage/membersListTable/membersListTable.scss, app/src/pages/organization/organizationProjectsPage/organizationProjectsPage.jsx, app/src/pages/organization/organizationProjectsPage/projectsListTable/projectsListTable.jsx, app/src/pages/organization/organizationProjectsPage/projectsListTable/projectsListTable.scss, app/src/pages/organization/organizationProjectsPage/projectsPageHeader/projectsPageHeader.scss, app/src/pages/organization/organizationUsersPage/organizationUsersPage.jsx, app/src/pages/organization/organizationUsersPage/organizationUsersPage.scss, app/src/pages/organization/projectTeamPage/projectTeamPage.jsx
=> EPMRPP-96409 || Set pagination component to sticky and adjusted scroll behavior

app/src/pages/outside/loginPage/loginPage.jsx
=> EPMRPP-96385 || Error message shown twice for inactive GitHub logins

app/src/common/utils/permissions/constants.js, app/src/common/utils/permissions/getRoleTitle.js, app/src/pages/organization/projectTeamPage/projectTeamListTable/projectTeamListTable.jsx
=> EPMRPP-95153 | Small adjustment to rename constants

app/src/common/utils/validation/validate.js, app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/recipientsContainer/recipientsContainer.jsx
=> EPMRPP-96328 || Impossible to save Notification rule when user has a dot in username

app/src/common/utils/permissions/getRoleTitle.js, app/src/pages/organization/projectTeamPage/projectTeamListTable/projectTeamListTable.jsx
=> EPMRPP-95153 || Adjust permissions to project role

app/src/components/widgets/singleLevelWidgets/charts/investigatedTrendChart/config/launchModeConfig.js, app/src/components/widgets/singleLevelWidgets/charts/launchStatisticsChart/config/utils.js
=> EPMRPP-96393 || Incorrect sorting in widgets and Firefox bug

app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.jsx
=> EPMRPP-88467 || Update "Create" button label in Notifications tab duplication modal

app/src/components/main/modal/darkModalLayout/darkModalLayout.scss
=> EPMRPP-91719 || Broken "Make decision" modal window background

app/src/pages/inside/launchesPage/launchesPage.jsx
=> EPMRPP-96056 || Impossible to import launch

app/src/controllers/log/constants.js, app/src/controllers/log/storageUtils.js
=> EPMRPP-96470 || Fix circular dependencies

app/src/pages/organization/organizationProjectsPage/modals/deleteProjectModal/deleteProjectModal.jsx, app/src/pages/organization/organizationProjectsPage/organizationProjectsPage.jsx, app/src/pages/organization/organizationProjectsPage/projectsListTable/projectActionMenu/projectActionMenu.jsx, app/src/pages/organization/organizationProjectsPage/projectsListTable/projectsListTable.jsx
=> EPMRPP-96870 & EPMRPP-96118 || Delete Button And Meatball Menu For Member-Editor

app/src/components/inputs/inputDropdown/inputDropdown.jsx
=> EPMRPP-80095 || Error when unchecking all defect types in filter

app/src/components/main/grid/gridHeader/headerCell/headerCell.jsx, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/uniqueErrorsGrid.jsx, app/src/pages/inside/uniqueErrorsPage/uniqueErrorsGrid/uniqueErrorsGrid.scss
=> EPMRPP-96647 || "All Unique Errors" dropdown changes its place

app/src/components/integrations/integrationProviders/emailIntegration/emailFormFields/emailFormFields.jsx
=> EPMRPP-97118 || There is no validation for the 'Username' field

app/src/components/main/analytics/events/adminServerSettingsPageEvents.js, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/authConfigurationTab/forms/ssoUsersForm/ssoUsersForm.jsx
=> EPMRPP-96943 || Add GA4 event to track instance invitation settings

app/src/pages/inside/stepPage/modals/makeDecisionModal/makeDecisionModal.jsx
=> EPMRPP-96967 || Cannot read properties of undefined (reading 'autoAnalyzed')

app/src/components/main/modal/darkModalLayout/darkModalLayout.scss
The modal decision window should cover the sidebar:
=> EPMRPP-97097 || The modal decision window should cover the sidebar

app/src/pages/inside/common/durationBlock/durationTooltip/durationTooltip.jsx, app/src/pages/inside/common/infoLine/parentInfo/parentInfo.jsx
=> EPMRPP-97287 || Duration is not shown for Nested Step on Log Level

app/src/common/urls.js
=> Update user endpoints

app/src/pages/inside/stepPage/stepGrid/defectType/issueList/issue/issueInfoTooltip/issueInfoTooltip.jsx
=> EPMRPP-97211 || BTS ticket tooltip. Show status only if exists

app/src/pages/inside/projectSettingsPageContainer/projectSettingsPageContainer.jsx
=> EPMRPP-92207 || Improve event "page_view" for Google Analytics 4

app/src/pages/inside/common/utils.js
=> EPMRPP-97810 || Several options are disabled in "Actions" dropdown

app/src/components/main/notification/notificationList/notificationList.scss
=> EPMRPP-97554 || Fixed Notifications z-index

app/src/pages/inside/logsPage/logsGrid/nestedStepHeader/nestedStepHeader.jsx
=> EPMRPP-98519 || Duration is not shown for Nested Step on Log Level

app/package-lock.json, app/package.json
=> Release 5.12.2

app/src/controllers/plugins/uiExtensions/createImportProps.js
=> EPMRPP-97046 || Manager without assignment to project cannot create QG

app/src/pages/inside/profilePage/personalInfoBlock/personalInfoBlock.jsx, app/src/pages/inside/profilePage/personalInfoBlock/photoControls/photoControls.jsx
=> EPMRPP-97474 || Update request for deleting user avatar

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/components/main/notification/notificationList/notificationList.jsx
=> EPMRPP-98910 || Page is crashed when deleting a project

app/src/pages/inside/projectSettingsPageContainer/content/analyzerContainer/analyzerContainer.jsx, app/src/pages/inside/projectSettingsPageContainer/projectSettingsPageContainer.jsx
=> EPMRPP-98992 || Hide 'Index Settings' tab for Members Viewers

app/src/pages/inside/launchesPage/modals/importLaunchModal/importLaunchModal.jsx
=> EPMRPP-99106 || Routing is broken when importing launch

app/src/common/urls.js
=> EPMRPP-99275 || Impossible to delete Test item

app/src/componentLibrary/popover/withPopover/withPopover.scss, app/src/layouts/common/appSidebar/helpAndService/previewPopover.scss, app/src/layouts/organizationsControl/organizationsPopover/organizationsItem/organizationsItemContentHeaderWithTooltip/organizationsItemContentHeaderWithTooltip.jsx
=> EPMRPP-95859 || Fix the tooltip on the sidebar's popover

app/src/components/main/filterButton/constants.js, app/src/components/main/filterButton/filterContent/filterInput/filterInput.jsx, app/src/components/main/filterButton/filterContent/filterInput/filterInput.scss, app/src/components/main/filterButton/messages.js, app/src/pages/instance/organizationsPage/organizationsPage.jsx, app/src/pages/instance/organizationsPage/organizationsPageHeader/organizationsFilter/messages.js, app/src/pages/instance/organizationsPage/organizationsPageHeader/organizationsFilter/organizationFilter.scss, app/src/pages/instance/organizationsPage/organizationsPageHeader/organizationsFilter/organizationsFilter.jsx, app/src/pages/organization/organizationProjectsPage/projectsPageHeader/projectsFilter/messages.js, app/src/pages/organization/organizationProjectsPage/projectsPageHeader/projectsFilter/projectsFilter.jsx, app/src/pages/organization/organizationProjectsPage/projectsPageHeader/projectsFilter/projectsFilter.scss
=> EPMRPP-98979 || Integrate multiselect component

app/src/components/main/filterButton/constants.js
=> EPMRPP-99423 ||  Incorrect search criteria value for external type

app/src/components/main/filterButton/filterButton.scss
=> EPMRPP-99262 || Wrong filter icon styles

app/src/pages/inside/dashboardItemPage/modals/widgetWizardModal/widgetWizardContent/widgetWizardContent.jsx
=> EPMRPP-99469 || Impossible to create widget when more than 50 dashboads are created

app/src/pages/inside/dashboardPage/dashboardList/dashboardTable/dashboardTable.jsx, app/src/pages/inside/dashboardPage/dashboardList/dashboardTable/dashboardTableColumns.jsx
=> EPMRPP-99543 || Dropdown in 'Duplicate' column not closing when another is opened  

app/src/components/main/analytics/AnalyticsWrapper.jsx
=> EPMRPP-99320 || Add event parameter kind to track type of projects

app/src/pages/admin/projectStatusPage/statusPageContent/statusPageContent.jsx
=> EPMRPP-99379 || Fix project monitoring perfomance issues

app/src/components/main/analytics/AnalyticsWrapper.jsx
=> Temporary disable entryType selection in AnalyticsWrapper.jsx

app/src/pages/common/numerableBlock/index.js, app/src/pages/common/numerableBlock/numerableBlock.jsx, app/src/pages/common/numerableBlock/numerableBlock.scss, app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/emptyStatePage.jsx, app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/img/environments-empty-state-inline.svg, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/environments/environments.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/environments/messages.js
=> implement environments empty page with reusable components

app/src/common/css/variables/newColors.scss, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/dropdownWithIcon/dropdownWithIcon.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/dropdownWithIcon/dropdownWithIcon.scss, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/dropdownWithIcon/index.js
Usage example 
``` js
<DropdownWithIcon
placeholder="placeholder"
selectedOption={{
label: 'Helen’s 1.4.2',
description: 'Updated by Olya on 1.2.2023 at 2:37 PM',
value: 2,
icon: icon2,
}}
options={[
{
label: 'Olya’s dataset',
description: 'Updated by Olya on 1.2.2023 at 2:37 PM',
value: 1,
icon,
},
{
label: 'Helen’s 1.4.2',
description: 'Updated by Olya on 1.2.2023 at 2:37 PM',
value: 2,
icon: icon2,
},
{
label: 'Project General Data',
description: 'Updated by Arjun Patel on 6.1.2024 at 1:23 PM',
value: '3',
icon,
},
]}
onChange={() => {
console.log('change');
}}
/>
```
=> Implement dropdown with icon

app/src/controllers/organization/projects/sagas.js
=> EPMRPP-99420 || Search field is not cleared after project deletion

app/src/components/main/notification/notificationList/notificationList.jsx, app/src/components/main/notification/notificationList/notificationList.scss
=> EPMRPP-98650 || Add test automation attribute for notification message

app/src/components/integrations/elements/integrationSettings/integrationForm/integrationForm.jsx, app/src/components/integrations/integrationProviders/samlIntegration/samlFormFields/samlFormFields.jsx
=> EPMRPP-99359 || Remove RP callback URL field from SAML integration form

app/package-lock.json, app/package.json, app/src/components/main/notification/notificationList/notificationList.jsx
=> EPMRPP-98650 || Add test automation attributes

app/localization/translated/be.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/src/components/main/analytics/events/ga4Events/dashboardsPageEvents.js, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/messages.js, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearch.jsx, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchContent/testCaseSearchContent.jsx, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchContent/testCaseSearchContent.scss, app/src/controllers/testItem/actionCreators.js, app/src/controllers/testItem/constants.js, app/src/controllers/testItem/index.js, app/src/controllers/testItem/sagas.js, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widget.jsx
=> EPMRPP-99051 || Test Case Search. Load more results

app/package-lock.json, app/package.json
=> EPMRPP-100146 || Eye icon is missing in Password field

app/src/components/main/analytics/events/common/ga4Utils.js, app/src/components/main/analytics/events/ga4Events/dashboardsPageEvents.js, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearch.jsx, app/src/controllers/testItem/sagas.js
=> EPMRPP-99289 || Add 3 event for search widget to track performance

app/src/components/inputs/inputConditionalAttributes/inputConditionalAttributes.scss, app/src/pages/inside/common/itemInfo/itemInfo.scss, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.scss
=> EPMRPP-100756 ||  Several UI bugs related to 'Test case search' widget

app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearch.jsx, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchContent/testCaseSearchContent.jsx, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchControl/testCaseSearchControl.jsx, app/src/controllers/testItem/sagas.js, app/src/pages/inside/stepPage/stepGrid/stepGrid.jsx, app/src/pages/inside/stepPage/stepGrid/stepGrid.scss
=> EPMRPP-100948 || EPMRPP-100948  || Request Timeout Issue and Debounce Fix for Search

app/localization/translated/be.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/src/components/inputs/inputConditionalAttributes/inputConditionalAttributes.scss, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/messages.js, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearch.jsx, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchContent/testCaseSearchContent.jsx, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchContent/testCaseSearchContent.scss, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchControl/testCaseSearchControl.jsx, app/src/controllers/testItem/sagas.js, app/src/pages/inside/common/itemInfo/itemInfo.scss, app/src/pages/inside/dashboardItemPage/widgetsGrid/widget/widgetHeader/widgetHeader.scss, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.jsx, app/src/pages/inside/stepPage/stepGrid/defectType/defectType.scss, app/src/pages/inside/stepPage/stepGrid/stepGrid.jsx, app/src/pages/inside/stepPage/stepGrid/stepGrid.scss
=> Sync feature/25.0.6 with rc/5.12.5

app/package-lock.json, app/package.json, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/datasets/createDatasetModal/createDatasetModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/datasets/dataset/dataset.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/datasets/dataset/dataset.scss, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/datasets/dataset/index.js, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/datasets/datasets.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/datasets/datasets.scss, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/headerControls/headerControls.scss, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/testData.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/variablesAndDatasets/index.js, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/variablesAndDatasets/variablesAndDatasets.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/variablesAndDatasets/variablesAndDatasets.scss, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/variablesControl/variablesControl.scss
https://github.com/user-attachments/assets/b85593fb-fdf6-46be-be15-802db3c43c99
=> Integrate dataset modal with datasets table

app/src/controllers/testItem/index.js, app/src/controllers/testItem/selectors.js, app/src/pages/inside/stepPage/stepGrid/groupHeader/groupHeader.jsx
=> EPMRPP-101005 || Launch name is not shown in group

app/src/pages/admin/projectStatusPage/statusPageContent/statusPageContent.jsx
=> EPMRPP-99379 || Fix project monitoring perfomance issues (#4227)[cherry-pick]

app/src/common/constants/localization.js, app/src/components/fields/fieldErrorHint/fieldErrorHint.jsx, app/src/pages/inside/productVersionPage/constants.js, app/src/pages/inside/productVersionPage/index.js, app/src/pages/inside/productVersionPage/messages.js, app/src/pages/inside/productVersionPage/productVersionHeader/deleteProductVersionModal/deleteProductVersionModal.jsx, app/src/pages/inside/productVersionPage/productVersionHeader/deleteProductVersionModal/deleteProductVersionModal.scss, app/src/pages/inside/productVersionPage/productVersionHeader/deleteProductVersionModal/index.js, app/src/pages/inside/productVersionPage/productVersionHeader/index.js, app/src/pages/inside/productVersionPage/productVersionHeader/popoverTools/popoverTools.jsx, app/src/pages/inside/productVersionPage/productVersionHeader/popoverTools/popoverTools.scss, app/src/pages/inside/productVersionPage/productVersionHeader/productVersionHeader.jsx, app/src/pages/inside/productVersionPage/productVersionHeader/productVersionHeader.scss, app/src/pages/inside/productVersionPage/productVersionHeader/renameProductVersionModal/index.js, app/src/pages/inside/productVersionPage/productVersionHeader/renameProductVersionModal/renameProductVersionModal.jsx, app/src/pages/inside/productVersionPage/productVersionPage.jsx
https://github.com/user-attachments/assets/93c11067-415c-488d-ac86-f8aa2ac5cb5a
=> Implement rename and delete product version modals

app/src/controllers/dashboard/constants.js, app/src/controllers/dashboard/sagas.js, app/src/controllers/dashboard/selectors.js
=> EPMRPP-99861 || Remove local sorting on UI

app/src/pages/admin/allUsersPage/allUsersGrid/projectsAndRolesColumn/projectsAndRolesColumn.jsx, app/src/pages/admin/allUsersPage/allUsersGrid/projectsAndRolesColumn/projectsAndRolesColumn.scss
=> EPMRPP-101096 || Add scroll to the user project list on

app/src/common/urls.js, app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchControl/entityProvider.jsx
=> EPMRPP-101514 || Fix testCaseSearch attribute autocomplete

app/src/components/main/analytics/events/ga4Events/dashboardsPageEvents.js
=> EPMRPP-101973 || Wrong condition for Add New Dashboard GA event

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/components/fields/fieldErrorHint/fieldErrorHint.jsx
=> EPMRPP-101151 ||  Wrong validation message is used for "API Key Name"

app/src/components/widgets/multiLevelWidgets/testCaseSearchTable/testCaseSearchControl/entityProvider.jsx
=> EPMRPP-102033 || TCS wrong value autocomplete param

app/src/pages/inside/dashboardPage/dashboardList/dashboardTable/dashboardTable.scss, app/src/pages/inside/dashboardPage/dashboardList/dashboardTable/dashboardTableColumns.jsx
=> EPMRPP-100566 || Permission to copy dashboard.

app/src/layouts/common/footer/footer.scss
=> EPMRPP-98960 || Footer text overlaps QG modal window

.github/workflows/release.yml
=> EPMRPP-101768 || Improve release flow

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/common/utils/validation/commonValidators.js, app/src/common/utils/validation/validate.js, app/src/common/utils/validation/validate.test.js, app/src/components/fields/fieldErrorHint/fieldErrorHint.jsx, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/linksAndBrandingTab/addLinkForm/addLinkForm.jsx
=> EPMRPP-102889 || Validation and Input maxlength adjustment

app/src/controllers/dashboard/constants.js, app/src/controllers/dashboard/reducer.js, app/src/controllers/dashboard/reducer.test.js, app/src/controllers/dashboard/sagas.js, app/src/controllers/dashboard/selectors.js
=> EPMRPP-99546 || Impossible to manage newly created dashboard after page reload

app/src/common/urls.js, app/src/pages/inside/profilePage/personalInfoBlock/personalInfoBlock.jsx, app/src/pages/inside/profilePage/personalInfoBlock/photoControls/photoControls.jsx
=> EPMRPP-97164 || Use new end-point for uploading user avatar

app/src/pages/admin/serverSettingsPage/serverSettingsTabs/linksAndBrandingTab/draggableLink/draggableLink.jsx
=> EPMRPP-103258 || No tooltip for the links with long URL

app/src/pages/inside/productVersionPage/linkedTestCasesTab/headerConfig/headerConfig.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/testData/variablesControl/variable/variable.scss
=> Fix build errors

app/src/components/widgets/singleLevelWidgets/tables/projectActivity/projectActivity.jsx
=> EPMRPP-103319 || Project activity panel widget is broken after upgrading

app/src/components/fields/fieldErrorHint/index.js, app/src/components/fields/index.js, app/src/pages/inside/common/externalLink/externalLink.jsx, app/src/pages/inside/common/externalLink/externalLink.scss, app/src/pages/inside/common/externalLink/index.js, app/src/pages/inside/projectSettingsPageContainer/content/elements/index.js, app/src/pages/inside/projectSettingsPageContainer/content/elements/infoBlockWithControl/infoBlockWithControl.jsx, app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/emptyStatePage.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/environments/createEnvironmentModal/createEnvironmentModal.jsx, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/environments/createEnvironmentModal/createEnvironmentModal.scss, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/environments/createEnvironmentModal/index.js, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/environments/createEnvironmentModal/messages.js, app/src/pages/inside/projectSettingsPageContainer/content/testLibrary/environments/environments.jsx
=> Implement initial create environment modal

app/src/pages/inside/common/statusDropdown/statusDropdown.scss, app/src/pages/inside/logsPage/logItemInfo/defectDetails/defectDetails.scss
=> EPMRPP-95360 || Launches. Log View. Dropdown arrows are not aligned at the center for item status and "Show Less"

app/package-lock.json, app/package.json
=> EPMRPP-94687 || Focus is lost after API Token field validation

app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx
=> EPMRPP-103523 || Error is displayed when clicking on failed integration

app/src/components/integrations/messages.jsx
=> EPMRPP-103330 || Update plugins descriptions

app/src/components/inputs/inputUserSearch/inputUserSearch.jsx, app/src/components/inputs/inputUserSearch/userItem/userItem.jsx, app/src/components/inputs/inputUserSearch/userItem/userItem.scss, app/src/pages/inside/common/userAvatar/userAvatar.scss
=> EPMRPP-103382 || Avatars have different sizes

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/components/main/notification/notificationList/notificationList.jsx, app/src/controllers/organization/projects/sagas.js
=> EPMRPP-103714 || Wrong validation message for creating duplicated project

app/localization/translated/be.json, app/localization/translated/es.json, app/localization/translated/ru.json, app/localization/translated/uk.json, app/localization/translated/zh.json, app/src/pages/inside/common/launchSuiteGrid/hamburger/hamburger.jsx
=> EPMRPP-104148 || Disable 'Make as important' launches controls

app/src/pages/inside/apiPage/apiPage.scss
=> EPMRPP-104522 || Schemas UI is broken in API Documentation page

app/src/pages/inside/projectSettingsPageContainer/projectSettingsPageContainer.jsx
=> EPMRPP-105185 || Fix settings tab extension name processing

app/src/pages/inside/productVersionPage/linkedTestCasesTab/tagList/tagList.scss, app/src/pages/inside/testCaseLibraryPage/testCaseList/testCaseList.scss, app/src/pages/inside/testCaseLibraryPage/testCaseList/testCaseSidePanel/testCaseSidePanel.scss
=> Side panel fix

app/src/pages/inside/testPlansPage/testPlansTable/testPlansTable.scss
=> test plans table design fix

app/src/pages/inside/common/assignments/instanceAssignment/instanceAssignment.tsx
=> EPMRPP-106373 || Fields disappear completely after deleting Organization

app/src/controllers/testCase/sagas.ts
=> Add missed yield

.github/workflows/build-feature-image.yaml, app/src/pages/admin/serverSettingsPage/serverSettingsTabs/linksAndBrandingTab/linksAndBrandingTab.scss, app/src/pages/inside/historyPage/historyView/constants.js, app/src/pages/inside/historyPage/historyView/historyControls/historyControls.jsx, app/src/pages/inside/historyPage/historyView/historyControls/historyControls.scss, app/src/pages/inside/historyPage/historyView/historyTable/historyCell/historyCell.jsx, app/src/pages/inside/historyPage/historyView/historyTable/historyItem/historyItem.jsx, app/src/pages/inside/historyPage/historyView/historyTable/historyItem/historyItem.scss, app/src/pages/inside/historyPage/historyView/historyTable/historyTable.jsx, app/src/pages/inside/historyPage/historyView/historyView.jsx, app/src/pages/inside/historyPage/historyView/utils.js
=> Feature. History table cell preview

app/src/pages/inside/historyPage/historyView/historyControls/historyControls.jsx, app/src/pages/inside/historyPage/historyView/historyView.jsx
=> EPMRPP-107322 || Duplicated GA events are sent

app/src/pages/outside/loginPage/pageBlocks/serviceVersionsBlock/serviceVersionItem/serviceVersionItem.jsx, app/src/pages/outside/loginPage/pageBlocks/serviceVersionsBlock/serviceVersionsBlockWithData.jsx
=> EPMRPP-107502 || Services are not displayed in "Versions" section

app/package-lock.json, app/package.json
=> EPMRPP-108169 || Update UI-Kit version

app/src/pages/inside/testCaseLibraryPage/expandedOptions/renameFolderModal/renameFolderModal.tsx
=> disable rename button in case of validation error
