- src/main/resources/public/js/src/launches/common/LaunchSuiteItemView.js
- src/main/resources/public/js/src/newWidgets/widgets/launchesTable/LaunchesTableView.js
- src/main/resources/public/templates/widgets/tpl-widget-filters-table-item.html
launch table widget) show interrupted and failed selection of items.
> EPMRPP-31255. Now clicking on failed statistics (launches grid and launch table widget) show interrupted and failed selection of items.

- src/main/resources/public/js/src/modals/modalAddProject.js
Because of backbone extension in updateBackbone.js file, now we need first of all close modals before routing. Otherwise routing will be skipped. (See Backbone.Router.prototype.route in updateBackbone.js)
> EPMRPP-31901. Fixed redirection after creating a new project.

- app/src/pages/inside/common/infoLine/infoLine.jsx
This a fix for hardcoded 7s in duration field.
Maybe it would be handy to solve a default case if props has no/undefined for start_time/end_time. Any suggestion is welcomed.
https://jiraeu.epam.com/browse/EPMRPP-35176
> EPMRPP-35176 This a fix for hardcoded 7s in duration field.

- .gitignore
- app/src/pages/inside/launchesPage/launchesPage.jsx
Not sure if the naming choices are all right. Probably fetchFunc should be renamed to onConfirm or callback, because it serves multiple purposes now, but that would require changes in many more files.
> [DNT] EPMRPP-34377: Selected launches have to disappear after merge finished

- app/src/pages/inside/filtersPage/filterGrid/filterGrid.scss
> EPMRPP-35247: React: Long filter name is overlapped the delete icon mobile view

- app/src/components/widgets/charts/launchesDurationChart/launchesDurationChart.scss
EPMRPP-37586 -  React: No OX axis is shown on the widget
> EPMRPP-37586 OX axis visibility fix in launchesDuration chart

- app/src/pages/inside/filtersPage/filterGrid/filterGrid.jsx
- app/src/pages/inside/filtersPage/filterGrid/filterName/filterName.jsx
- app/src/pages/inside/filtersPage/filterGrid/filterName/filterName.scss
- app/src/pages/inside/filtersPage/filtersPage.jsx
Solution:
1. Add `NavLink` to redirect to Launches page when the user click on the filter name
2. Call `showFilterOnLaunchesAction` when the user click on the filter name to display filter on Launches page in case DISPLAY ON LAUNCHES was set to `off`
> EPMRPP-34192: add redirect to launches page when click on filter name

- app/src/components/main/grid/gridHeader/headerCell/headerCell.jsx
- app/src/pages/admin/projectEventsPage/eventsGrid/eventsGrid.jsx
Also, disable sorting handler for non-sortable columns.
Other columns will remain non-sortable for now. See this [comment](https://jiraeu.epam.com/browse/EPMRPP-38397?focusedCommentId=3913265&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3913265)
> EPMRPP-38397: Add sorting icon to "object name" column.

- app/src/pages/inside/common/launchFiltersContainer/launchFiltersContainer.jsx
Case:
1. Open launches page
2. Click "Add filter"
3. Change "name" field
4. Check request
**Expected result**
Request contains: `filter.cnt.name=demo`
**Actial result**
Request contains: `newFilter={"filter.cnt.name":"demo"}`
> EPMRPP-38393: Fix incorrect launch filter query

- app/src/common/utils/connectRouter.jsx
- app/src/common/utils/routingUtils.js
- app/src/controllers/pages/actionCreators.js
1. Go to suites level
2. Add any filter with
3. Input any value to that filter
4. Remove filter
**Expected result:**
Filter removed from query parameters.
**Actual result:**
Filter remains in query with an empty value.
1. Go to the log level
2. Change log level
3. Check "Logs with Attachment" checkbox
**Expected result:**
Both parameters are presented in URL
**Actual result:**
Log level parameter is replaced with checkbox parameter
> Fix namespaced query parameters update

- app/src/components/widgets/charts/passingRatePerLaunch/passingRatePerLaunch.jsx
**Preconditions:**
Passing rate per Launch widget is created
**Steps**:
1) Login to RP -> go to Dashboard page
2) Change the size of Passing rate per Launch widget using arrows in the lower right corner
**Expected result:**
the widget should adjust to resize
> EPMRPP-38837 - React. "Passing rate per Launch" widget bar goes out of borders when changing its size

- main.go
Fixes `Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data: <URL> stats.g.doubleclick.net *.epam.com *.uservoice.com"
` console message and its consequences.
> EPMRPP-36908: fix - React: Markdown options are not applied

- app/localization/translated/be.json
- app/localization/translated/ru.json
- app/src/components/main/notification/notificationList/notificationListItem/notificationItem.jsx
- app/src/controllers/dashboard/sagas.js
1) Go to RP -> Dashboard tab
2) Click 'Add New Dashboard' button
3) Fill in the fields in 'Add New Dashboard' modal window
4) Click 'Add' button
Actual result: no notification appears
Expected result: 'Dashboard has been added' notification appears at the bottom in green
> EPMRPP-37114 - REACT. There is no notification after adding a dashboard

- app/src/pages/inside/stepPage/retries/retriesList/retry/retry.jsx
- app/src/pages/inside/stepPage/retries/retriesList/retry/retry.scss
Create launch (Suite>Test>Step(with retry))
Go to Step view
Click on the link with count of retried elements 
Check displayed statuses of retried elements 
Expected result: Statuses are not overlapped, start time is displayed for each item
Actual result: Statuses are overlapped, items with status "in progress" has no start time
> EPMRPP-38750 - React: Statuses of retried elements are overlapped on step view

- app/src/pages/inside/common/itemInfo/itemInfo.scss
Last fix with `overflow-wrap` didn't work appropriately.
> EPMRPP-38839: reopened - incorrect hyphenation of launch name

- app/src/components/inputs/inputConditional/inputConditional.jsx
- app/src/components/inputs/inputConditionalTags/inputConditionalTags.jsx
- app/src/components/inputs/inputDropdown/inputDropdown.jsx
- app/src/components/inputs/inputDropdownSorting/inputDropdownSorting.jsx
- app/src/components/inputs/inputTimeDateRange/inputTimeDateRange.jsx
- app/src/components/main/colorPicker/colorPicker.jsx
- app/src/pages/inside/common/defectTypeSelector/defectTypeSelector.jsx
- app/src/pages/inside/common/launchFiltersToolbar/allLatestDropdown/allLatestDropdown.jsx
Case 1:
- open widget wizard modal
- select "LaunchStatistics" widget
- go to second step
- click on empty place in the modal
**ER**: nothing happens
**AR**: preview rerenders on every click
Case 2:
- open any page with any of changed components present (for example: launches page with selected filter)
- open react devtools
- open preferences and select "Highlight Updates"
- click on empty place on a page
**ER**: nothing happens
**AR**: some of components are marked with blue rectengles which indicates rerenders
> Fix unnecessary renders on blur and clicking outside of some popups

- app/src/components/widgets/singleLevelWidgets/charts/launchStatisticsChart/launchStatisticsChart.jsx
Fix for displaying empty data for `Launch statistics chart` (see the screenshot below).
> EPMRPP-41362 Fix Launch statistics chart data calculating

- app/src/pages/inside/logsPage/logsGrid/logMessageBlock/logMessageBlock.scss
Fix for [this](https://github.com/reportportal/reportportal/issues/150) issue.
> Logs grid. Set white-space css property to pre-wrap for log message

- Makefile
- readme.md
gofumports was completely removed from gofumpt version 0.2.0 ([release notes](https://github.com/mvdan/gofumpt/releases)).
@avarabyeu could you please help with this? Should we migrate this style utilities to the new version?
I'll merge this quick fix to repair jenkins build, but it is still potentially unreliable.
> Test CI build

- app/package-lock.json
- app/package.json
- app/webpack/base.config.js
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed
Here is installed the last of the 3rd version of `swagger-ui-react` lib, which is not the last one. Since v.4, lib has a peer dependency by react v. >=17.0.
> EPMRPP-74158 || fix api page error

- app/src/componentLibrary/modal/modalLayout/modalLayout.scss
- app/src/controllers/project/actionCreators.js
- app/src/controllers/project/constants.js
- app/src/controllers/project/reducer.js
- app/src/controllers/project/sagas.js
- app/src/controllers/project/selectors.js
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx
EPMRPP-78105 || Notifications preloader, EPMRPP-78115 || Modal window paddings fix
> EPMRPP-78105 || Notifications preloader, EPMRPP-78115 || Modal window fix

- app/src/componentLibrary/autocompletes/singleAutocomplete/singleAutocomplete.jsx
Now when you try to delete the whole value from the input, the previous does not remains in input field
> EPMRPP-78297 || fix deleting attribute values

- app/src/components/main/analytics/AnalyticsWrapper.jsx
ep.is_admin was removed.
Fix errors witch you may see in browser`s console related with Universal GA.
> EPMRPP-78833 || Remove is_admin from event_parameter

- app/src/components/main/analytics/AnalyticsWrapper.jsx
If user isAdmin, projectId doesn't send.
> EPMRPP-79973 || Change projectId parameter for GA4

- app/src/pages/common/settingsPage/notificationsTab/notificationsTab.jsx
Now, when we do not have any attr, we send no attr with events.
> EPMRPP-80757 || Add additional logic to Notification events

- app/src/pages/common/settingsPage/notificationsTab/modals/addEditNotificationCaseModal/addEditNotificationCaseModal.jsx
- app/src/pages/common/settingsPage/notificationsTab/modals/addEditNotificationCaseModal/notificationCaseFormFields/notificationCaseFormFields.jsx
- package-lock.json
Now when we have less than one attribute the options AND/OR are disabled. It becomes active only when at least two attr are added.
> EPMRPP-80671 || Improve attribute options in Notifications

- app/src/controllers/uniqueErrors/sagas.js
According to already existing logic, if we have no integrations, we wait for FETCH_INTEGRATIONS_SUCCESS action using 'take' effect, wich blocks execution. We need to add fetchIntegrations action, to get integrations one more time, and after that FETCH_INTEGRATIONS_SUCCESS action receives and function execution continue.
> EPMRPP-80151 || Fix Unique errors page

- app/src/components/main/analytics/events/ga4Events/profilePageEvent.js
- app/src/components/main/analytics/events/profilePageEvents.js
- app/src/pages/inside/profilePage/localizationBlock/localizationBlock.jsx
[EPMRPP-80423 ](https://jiraeu.epam.com/browse/EPMRPP-80423)
change universal analytics to ga4
> EPMRPP-80423 || add google event for profile

- app/src/common/urls.js
Request /v1/demo/item call endpoint for demo data generation not test item creation
Url  for demo data generation changed to /v1/demo/{projectName}/generate to avoid url collision.
Also required to change url on ui
> EPMRPP-81046 || Impossible to report test items to project with "demo" name

- app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx
- app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.scss
- app/src/components/integrations/integrationProviders/jiraIntegration/jiraConnectionFormFields/jiraConnectionFormFields.scss
[EPMRPP-80924](https://jiraeu.epam.com/browse/EPMRPP-80924)
AND 
[EPMRPP-79333](https://jiraeu.epam.com/browse/EPMRPP-79333)
Before: 
---
After: 
---
> EPMRPP-80924 || fix wrong spacing in integration tab

- app/localization/translated/be.json
- app/localization/translated/ru.json
- app/localization/translated/uk.json
- app/src/controllers/dashboard/constants.js
- app/src/controllers/dashboard/index.js
- app/src/controllers/dashboard/reducer.js
- app/src/controllers/dashboard/sagas.js
- app/src/controllers/dashboard/selectors.js
- app/src/pages/inside/common/dashboardPageHeader/addDashboardButton/addDashboardButton.jsx
- app/src/pages/inside/common/dashboardPageHeader/dashboardPageHeader.jsx
- app/src/pages/inside/dashboardPage/dashboardPage.jsx
Now users can't create more than 300 dashboards.
If the user already has more than 300 dashboards, he needs to delete them, until the total amount becomes less than 300 to have the ability to create new ones.
> EPMRPP-81029 || Add dashboard creation limit

- app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleAutocomplete.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/recipientsContainer/recipientsContainer.jsx
[EPMRPP-79270](https://jiraeu.epam.com/browse/EPMRPP-79270)
Before: 
---
After: 
---
> EPMRPP-79270 || remove placeholder if recipient added

- app/src/controllers/plugins/reducer.js
- app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationCollection/integrationCollection.jsx
[EPMRPP-77501](https://jiraeu.epam.com/browse/EPMRPP-77501)
sorted integrations by creationDate after add new item
> EPMRPP-77501 || sorted integrations after add new item

- app/package-lock.json
- app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx
[EPMRPP-81141](https://jiraeu.epam.com/browse/EPMRPP-81141)
hidden manage buttons when user without manage permissions
> EPMRPP-81141 || hidden manage buttons when user without manage permissions

- app/src/components/inputs/inputConditionalAttributes/inputConditionalAttributes.jsx
- app/src/components/main/attributeList/editableAttribute/attributeEditor/attributeEditor.jsx
[EPMRPP-81198](https://jiraeu.epam.com/browse/EPMRPP-81198)
in other places of the application we have the Editable capability and we have props attribute.edited, but in this place we create new filter and this.props.attribute.edited === undefined
Before: 
https://jiraeu.epam.com/secure/attachment/2131767/81198.mp4 
---
After: 
---
> EPMRPP-81198 || fixed validation attribute value when you create launch filter

- app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx
- app/src/components/integrations/elements/integrationSettings/integrationForm/integrationForm.jsx
- app/src/components/integrations/elements/integrationSettings/integrationSettings.jsx
[EPMRPP-81141](https://jiraeu.epam.com/browse/EPMRPP-81141)
after talk with Ashat and Helen Bobrova, we came to the conclusion that the form buttons should be hidden too in scope of this bug
Before: 
---
After: 
---
> EPMRPP-81141 || addition to fix for EPMRPP-81141: form buttons are hidden too

- app/src/components/widgets/multiLevelWidgets/componentHealthCheckTable/columns/nameColumn.jsx
- app/src/components/widgets/multiLevelWidgets/componentHealthCheckTable/componentHealthCheckTable.scss
- app/src/components/widgets/multiLevelWidgets/componentHealthCheckTable/messages.jsx
[EPMRPP-81599](https://jiraeu.epam.com/browse/EPMRPP-81599)
Undone points: 3. The Value container size is flexible and adapts to the size of the widget.
What can be improved: variable names
---
After:
> EPMRPP-81599 || change ellipsis for health check widget name

- app/src/controllers/log/index.js
- app/src/controllers/log/selectors.js
- app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/logItemInfoTabs.jsx
- app/src/pages/inside/logsPage/logsGridToolbar/logsGridToolbar.jsx
- app/src/pages/inside/logsPage/logsGridWrapper/logsGridWrapper.jsx
Also in this PR:
`isLogPageWithOutNestedSteps` usage removed from 'LogsGridToolbar' as it is an opposite to `isLogPageWithNestedSteps` which is already used inside of the component.
> EPMRPP-82778 || Show 'Next Error' feature only for detailed log view

- Dockerfile
Decided to remove `lint` and `test` commands form `Dockerfile` to speed up image building process.
Linting and testing steps are still present as CI workflow steps.
> Fix long UI service docker image builds

- nginx.conf
Permission denied error when run as non-root. See Common Issues - https://hub.docker.com/r/nginxinc/nginx-unprivileged
> nginx-unprivileged common issue patch

- app/src/controllers/filter/reducer.js
This fix allows store unsaved filters instead of replacing them
> EPMRPP-78737 || Unsaved filter replaces

- app/src/components/fields/dynamicFieldsSection/dynamicField/dynamicField.jsx
- app/src/components/fields/dynamicFieldsSection/dynamicField/dynamicField.scss
- app/src/components/fields/dynamicFieldsSection/dynamicFieldShape.js
- app/src/components/fields/dynamicFieldsSection/dynamicFieldsSection.jsx
- app/src/components/fields/dynamicFieldsSection/fields/autocompleteField.jsx
- app/src/components/fields/dynamicFieldsSection/fields/multipleAutocompleteField.jsx
- app/src/components/integrations/elements/bts/btsPropertiesForIssueForm/btsPropertiesForIssueForm.jsx
- app/src/components/integrations/elements/bts/btsPropertiesForIssueForm/btsPropertiesForIssueForm.scss
- app/src/components/integrations/elements/bts/utils.js
- app/src/pages/inside/projectSettingsPageContainer/content/elements/fieldElement/fieldElement.jsx
Usage of `FormField` & `IntegrationFormField` replaced with `FieldElement`.
Styles for Post issue modal will be adjusted in the scope of EPMRPP-87463.
> EPMRPP-87336 || Add BTS field description

- app/src/controllers/auth/index.js
- app/src/controllers/auth/selectors.js
- app/src/pages/inside/apiPage/apiPage.jsx
> EPMRPP-89400 || Set bearer token in api doc

- app/src/layouts/appLayout/projectSidebar/organizationsControl/organizationsControl.scss
- app/src/layouts/common/appSidebar/appSidebar.scss
- app/src/layouts/common/appSidebar/userControl/userControl.scss
> EPMRPP-90680 || Popover is broken in sidebar

- app/localization/translated/be.json
- app/localization/translated/ru.json
- app/localization/translated/uk.json
- app/localization/translated/zh.json
- app/src/controllers/project/selectors.js
- app/src/pages/inside/projectSettingsPageContainer/content/elements/notificationRuleContent/notificationRuleContent.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/constants.js
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/messages.js
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.scss
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/propTypes.js
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/ruleGroup/ruleGroup.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/utils.js
> EPMRPP-89476 || CRUD for Slack Notification rule with dynamic fields

- app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/ruleGroup/ruleGroup.jsx
> EPMRPP-90820 || Incorrect description for Slack rules

- app/package-lock.json
- app/package.json
- app/src/componentLibrary/attributeList/attributeList.jsx
- app/src/componentLibrary/modal/modalLayout/modalFooter/modalFooter.jsx
- app/src/components/containers/AttributeListFormField/attributeListFormField.jsx
- app/src/components/integrations/elements/integrationSettings/integrationForm/integrationForm.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/analyzerContainer/autoAnalysis/autoAnalysis.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/analyzerContainer/indexSettings/indexSettings.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/analyzerContainer/similarItems/similarItems.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/analyzerContainer/uniqueErrors/uniqueErrors.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/defectTypes/defectTypes.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/emptyStatePage.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationHeader/integrationHeader.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/emptyRuleState/emptyRuleState.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/ruleGroup/ruleGroup.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/patternAnalysis/patternAnalysisContent/patternAnalysisContent.jsx
- app/src/pages/inside/projectSettingsPageContainer/generalTab/generalTab.jsx
> EPMRPP-91235 || button topaz variant fix

- app/src/components/main/analytics/events/ga4Events/projectSettingsPageEvents.js
- app/src/controllers/project/actionCreators.js
- app/src/controllers/project/sagas.js
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/LinkComponent/LinkComponent.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/footer/footer.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/helpPanel/helpPanel.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/addEditNotificationModal.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/notifications/ruleGroup/ruleGroup.jsx
> EPMRPP-90835 || Add GA4 events for Notifications

- app/localization/translated/be.json
- app/localization/translated/es.json
- app/localization/translated/ru.json
- app/localization/translated/uk.json
- app/localization/translated/zh.json
- app/src/common/urls.js
- app/src/controllers/dashboard/index.js
- app/src/controllers/dashboard/sagas.js
- app/src/controllers/dashboard/selectors.js
- app/src/pages/inside/common/dashboardPageHeader/addDashboardButton/addDashboardButton.jsx
- app/src/pages/inside/common/dashboardPageHeader/dashboardPageHeader.jsx
- app/src/pages/inside/dashboardPage/dashboardPage.jsx
- app/src/routes/routesMap.js
> EPMRPP-88780 || Increase the dashboard limit per project

- app/src/pages/inside/historyPage/historyToolbar/actionPanel/historyActionPanel.jsx
> EPMRPP-95913 || Remove 'Compare' button on History Table for Member Viewer

- app/localization/translated/be.json
- app/localization/translated/es.json
- app/localization/translated/ru.json
- app/localization/translated/uk.json
- app/localization/translated/zh.json
- app/src/common/constants/accountType.js
- app/src/pages/admin/allUsersPage/usersToolbar/usersEntities.jsx
> EPMRPP-98419 || Add ability to filter users by SCIM type

- app/src/pages/common/membersPage/userNameCell/userNameCell.jsx
- app/src/pages/common/membersPage/userNameCell/userNameCell.scss
> EPMRPP-98469 || Fix truncation of User Full Name in Organizations

- app/src/common/utils/validation/validate.js
- app/src/common/utils/validation/validate.test.js
- app/src/pages/admin/allUsersPage/usersToolbar/actionPanel/actionPanel.jsx
- app/src/pages/inside/profilePage/modals/changePasswordModal/changePasswordModal.jsx
- app/src/pages/inside/profilePage/personalInfoBlock/personalInfoBlock.jsx
- app/src/pages/outside/loginPage/pageBlocks/changePasswordBlock/changePasswordForm/changePasswordForm.jsx
- app/src/pages/outside/registrationPage/registrationForm/registrationForm.jsx
- app/src/pages/outside/registrationPage/registrationPageContainer.jsx
> EPMRPP-100064 || Exclude spaces from password validation

- app/src/common/constants/pluginNames.js
- app/src/components/integrations/constants.js
- app/src/components/integrations/containers/integrationInfoContainer/instancesSection/instancesSection.jsx
- app/src/components/integrations/containers/integrationInfoContainer/integrationInfoContainer.jsx
- app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx
- app/src/components/integrations/elements/integrationSettings/integrationSettings.jsx
- app/src/components/integrations/index.js
- app/src/pages/admin/pluginsPage/pluginsListItems/pluginsItem/pluginsItem.jsx
- app/src/pages/admin/pluginsPage/pluginsTabs/installedTab/installedTab.jsx
- app/src/pages/inside/common/btsIntegrationSelector/btsIntegrationSelector.jsx
- app/src/pages/inside/common/itemInfo/itemInfo.jsx
- app/src/pages/inside/logsPage/logItemInfo/logItemInfoTabs/sauceLabsIntegrationButton/sauceLabsIntegrationButton.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/index.js
- app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationHeader/integrationHeader.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationInfo.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationsListItem/integrationsListItem.jsx
This pull request focuses on removing the `PLUGIN_NAME_TITLES` constant and updating the code to use the `details.name` property directly for plugin names. The changes span multiple files and components, ensuring that the plugin name is consistently retrieved from the `details` object.
Key changes include:
* [`app/src/components/integrations/containers/integrationInfoContainer/integrationInfoContainer.jsx`](diffhunk://#diff-b5a3dc458a50031423d560a179934eba5282ca74b09855529709897241710e97L25): Removed the import of `PLUGIN_NAME_TITLES` and updated the `pluginTitle` to use `details.name` instead. [[1]](diffhunk://#diff-b5a3dc458a50031423d560a179934eba5282ca74b09855529709897241710e97L25) [[2]](diffhunk://#diff-b5a3dc458a50031423d560a179934eba5282ca74b09855529709897241710e97L73-R72)
* …
> Adjust plugin display name

- app/src/components/fields/searchField/searchField.jsx
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/filterBlock/filterBlock.jsx
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/filterBlock/filterBlock.scss
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/filterBlock/index.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/filterBlock/messages.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/headerConfig/headerConfig.jsx
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/headerConfig/headerConfig.scss
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/headerConfig/index.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/headerConfig/messages.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/index.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/linkedTestCasesTab.jsx
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/linkedTestCasesTab.scss
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/messages.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/tagList/index.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/tagList/messages.js
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/tagList/mockData.jsx
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/tagList/tagList.jsx
- app/src/pages/inside/productVersionPage/linkedTestCasesTab/tagList/tagList.scss
- app/src/pages/inside/productVersionPage/productVersionPage.jsx
- app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/emptyStatePage.scss
> implement linked test cases content

- app/src/components/main/grid/gridHeader/headerCell/headerCell.jsx
> Release 5.14.1
